"""量化前端关键字符串守卫（指向 quant.js / partials，不再读已拆空的 index.html/app.js）。"""

import os
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)


class TestWebQuantJsGuards(unittest.TestCase):
    def _read(self, *parts):
        path = os.path.join(ROOT, *parts)
        with open(path, encoding="utf-8") as f:
            return f.read()

    def test_quant_js_neutral_compare_and_export(self):
        js = self._read("web", "static", "js", "quant.js")
        export_js = self._read("web", "static", "js", "quant", "domain_export.js")
        self.assertIn("QUANT_EXPORT_PRESETS", js)
        self.assertIn('previewQuantExport("markdown")', js)
        self.assertIn("runQuantInterpret", js)
        self.assertIn("forceOffline: true", js)
        self.assertIn("llmAvailable", export_js)
        self.assertIn("offline: useOffline", export_js)
        self.assertIn("readDailyBtOverrides", export_js)
        self.assertIn("quant_daily_bt_opts_v3", export_js)
        self.assertIn("quant-daily-top-k", export_js)

    def test_daily_bt_option_js(self):
        export_js = self._read("web", "static", "js", "quant", "domain_export.js")
        self.assertIn("readDailyBtOverrides", export_js)
        self.assertIn("{ preset, ...readDailyBtOverrides() }", export_js)

    def test_partials_have_key_controls(self):
        panel = self._read("web", "static", "partials", "quant_panel.html")
        self.assertIn('id="quant-daily-fold"', panel)
        self.assertIn('id="quant-daily-top-k"', panel)
        self.assertIn('id="quant-daily-horizon"', panel)
        self.assertIn('id="quant-daily-lookback"', panel)
        self.assertIn('<option value="30" selected>30</option>', panel)
        self.assertIn('<option value="60">60</option>', panel)
        self.assertIn('<option value="90">90</option>', panel)
        self.assertIn('<option value="3" selected>3</option>', panel)
        self.assertIn('<option value="1" selected>1日</option>', panel)
        self.assertIn("quant-interpret-offline", panel)
        self.assertIn("规则解读", panel)
        self.assertIn("quant-interpret-neutral", panel)
        self.assertIn("quant-ols-run", panel)
        self.assertIn("quant-ols-code", panel)
        self.assertIn("quant-probe-picker", panel)
        self.assertIn("quant-ols-code-menu", panel)
        self.assertIn("quant-probe-run", panel)
        self.assertIn("quant-global-fold", panel)
        self.assertIn("quant-section-threshold", panel)
        self.assertIn("quant-threshold-apply", panel)
        self.assertIn("quant-section-cross", panel)
        self.assertIn("对照验证", panel)
        self.assertIn("quant-ols-summary", panel)
        self.assertIn("quant-factor-list", panel)
        self.assertIn("quant-ridge-lambda", panel)
        self.assertIn("quant-cross-list", panel)
        self.assertIn("quant-weight-table-wrap", panel)
        self.assertIn("quant-cross-run", panel)

        self.assertIn('id="quant-section-minute"', panel)
        self.assertIn('id="quant-cluster-minute-refresh"', panel)
        self.assertIn('id="quant-cluster-minute-topup"', panel)
        self.assertIn("强更 5m", panel)
        self.assertIn("增量补齐", panel)
        self.assertIn('id="quant-cluster-bars-topup"', panel)
        self.assertIn("强更日 K", panel)
        minute_js = self._read("web", "static", "js", "quant", "cluster_minute_ui.js")
        self.assertIn("installClusterMinuteUi", minute_js)
        self.assertIn("/api/quant/cluster-minute/status", minute_js)
        self.assertIn("/api/jobs/cluster-minute-refresh", minute_js)
        self.assertIn('mode: modeS', minute_js)
        self.assertIn("startTopup", minute_js)
        self.assertIn("unwrapJobSnap", minute_js)
        self.assertIn("applyJobFailure", minute_js)
        self.assertIn("syncJobSlot", minute_js)
        bars_js = self._read("web", "static", "js", "quant", "cluster_bars_ui.js")
        self.assertIn("unwrapJobSnap", bars_js)
        self.assertIn("syncJobSlot", bars_js)
        self.assertIn("applyJobFailure", bars_js)
        self.assertIn("startTopup", bars_js)
        self.assertIn('mode: modeS', bars_js)
        self.assertIn("quant-cluster-bars-topup", bars_js)
        job_js = self._read("web", "static", "js", "quant", "cluster_job_ui.js")
        self.assertIn("unwrapJobSnap", job_js)
        quant_js = self._read("web", "static", "js", "quant.js")
        self.assertIn("installClusterMinuteUi", quant_js)

        watching = self._read("web", "static", "partials", "watching_panel.html")
        self.assertIn('id="watching-data-offline"', watching)
        self.assertIn("仅本地仓", watching)
        self.assertIn(
            "data_offline.js",
            self._read("web", "static", "js", "quant", "domain_watching.js"),
        )
        self.assertIn(
            "data_warehouse_topup.js",
            self._read("web", "static", "js", "quant", "domain_watching.js"),
        )
        self.assertIn(
            "ensureWarehouseTopup",
            self._read("web", "static", "js", "quant", "domain_watching.js"),
        )
        self.assertIn(
            "offlineOnlyQuery",
            self._read("web", "static", "js", "quant", "domain_watching.js"),
        )
        offline_js = self._read("web", "static", "js", "data_offline.js")
        self.assertIn('return "offline_only=1"', offline_js)
        self.assertIn("增量补齐", offline_js)
        topup_js = self._read("web", "static", "js", "data_warehouse_topup.js")
        self.assertIn("ensureWarehouseTopup", topup_js)
        self.assertIn("/api/quant/cluster-bars/refresh", topup_js)
        self.assertIn("/api/quant/cluster-minute/refresh", topup_js)
        self.assertIn('mode: "topup"', topup_js)
        follow = self._read("web", "static", "partials", "follow_panel.html")
        self.assertIn('id="follow-data-offline"', follow)
        paper_js = self._read("web", "static", "js", "paper.js")
        self.assertIn("offlineOnlyQuery", paper_js)
        self.assertIn("installDataOfflineToggle", paper_js)
        self.assertIn("ensureWarehouseTopup", paper_js)
        self.assertIn("bindHost", paper_js)
        self.assertIn("fetchHoldingScoresWithRetry", paper_js)
        self.assertIn("applyHoldingsScorePack", paper_js)
        tip_js = self._read("web", "static", "js", "score_tooltip.js")
        self.assertIn("attachDismiss(tip, anchor", tip_js)
        hold_tip_js = self._read("web", "static", "js", "paper", "holding_chg_tip.js")
        self.assertIn("data-hold-chg-code", hold_tip_js)
        rb = self._read("web", "static", "js", "paper", "cluster_rebalance.js")
        self.assertIn("offline_only: true", rb)
        self.assertIn("ensureWarehouseTopup", rb)
        self.assertIn("getDataOfflineOnly", rb)

        replay = self._read("web", "static", "partials", "replay_panel.html")
        self.assertIn("quant-neutral-compare-table", replay)
        self.assertIn('id="replay-kpi-row"', replay)
        self.assertIn('id="replay-kpi-return"', replay)

    def test_t0_trade_table_has_nc_oc_column(self):
        table_js = self._read("web", "static", "js", "paper", "t0_table.js")
        self.assertIn("y_nc_oc", table_js)
        self.assertIn("fmtNowcastOcCell", table_js)
        self.assertNotIn('">y_nc_oc</th>', table_js)

    def test_score_tooltip_nc_oc_tip_mode(self):
        tip_js = self._read("web", "static", "js", "score_tooltip.js")
        self.assertIn('tip === "nc_oc"', tip_js)
        self.assertIn("formatNcOcSection", tip_js)
        self.assertIn('tipMode === "nc_oc"', tip_js)

    def test_score_tooltip_path_feat_labels_zh(self):
        tip_js = self._read("web", "static", "js", "score_tooltip.js")
        self.assertIn('ret_open_to_tau: "开盘→τ 收益 %"', tip_js)
        self.assertIn('range_pct: "前缀振幅 %"', tip_js)
        self.assertIn('pullback_from_high: "自高回撤 %"', tip_js)
        self.assertIn("PATH_FEAT_LABELS[k]", tip_js)
        self.assertIn('key === "path" && k && PATH_FEAT_LABELS[k]', tip_js)

    def test_y_nc_column_uses_resolve_nowcast_cc_score(self):
        fmt_js = self._read("web", "static", "js", "paper", "fmt.js")
        table_js = self._read("web", "static", "js", "paper", "t0_table.js")
        self.assertIn("resolveNowcastCcScore", fmt_js)
        self.assertIn("nowcast: resolveNowcastCcScore", table_js)
        self.assertIn("resolveNowcastScore(it)", fmt_js)
        self.assertIn("return resolveNowcastCcScore(it)", fmt_js)
        self.assertIn("Y_NC_TITLE", fmt_js)
        self.assertIn("Y_NC_OC_TITLE", fmt_js)
        self.assertIn("nowcast = nc", fmt_js)

    def test_follow_panel_nc_terminology(self):
        panel = self._read("web", "static", "partials", "follow_panel.html")
        self.assertIn("nowcast OC", panel)
        self.assertIn("nc闸", panel)
        self.assertIn("异号闸", panel)

    def test_t0_trades_fullscreen_toggle(self):
        table_js = self._read("web", "static", "js", "paper", "t0_table.js")
        css = self._read("web", "static", "css", "follow.css")
        self.assertIn("data-trades-fs-toggle", table_js)
        self.assertIn("paper-t0-trades-panel", table_js)
        self.assertIn("bindT0TradesFullscreen", table_js)
        self.assertIn(".paper-t0-trades-panel.is-fs", css)

    def test_t0_trade_date_col_fits_iso_day(self):
        table_js = self._read("web", "static", "js", "paper", "t0_table.js")
        css = self._read("web", "static", "css", "follow.css")
        self.assertIn('date: "104px"', table_js)
        self.assertIn("fmtTradeDate", table_js)
        self.assertIn("width: 104px", css)
        self.assertIn(".paper-t0-col-date", css)

    def test_live_t0_tables_omit_realized_pair(self):
        table_js = self._read("web", "static", "js", "paper", "t0_table.js")
        ui_js = self._read("web", "static", "js", "paper", "t0_ui.js")
        self.assertIn("fmtPredRealizedText", table_js)
        self.assertIn("showRealized = true", table_js)
        self.assertEqual(ui_js.count("showRealized: false"), 2)

    def test_holdings_table_has_t0_column(self):
        island_js = self._read("web", "static", "js", "holdings_table_island.js")
        badge_js = self._read("web", "static", "js", "paper", "holding_t0_badge.js")
        css = self._read("web", "static", "css", "follow.css")
        self.assertIn('id: "t0"', island_js)
        self.assertIn("holdingT0BadgeHtml", island_js)
        self.assertIn("t0_intraday", island_js)
        self.assertIn("paper-hold-t0-badge", badge_js)
        self.assertIn(".paper-hold-t0-badge", css)

    def test_holdings_table_has_y_path_column(self):
        island_js = self._read("web", "static", "js", "holdings_table_island.js")
        ui_js = self._read("web", "static", "js", "paper", "holdings_ui.js")
        sort_js = self._read("web", "static", "js", "paper", "holdings_sort.js")
        self.assertIn('id: "score_path"', island_js)
        self.assertIn('label: "y_path"', island_js)
        self.assertIn("resolvePathScore", island_js)
        self.assertIn("score_path: \"path\"", island_js)
        self.assertIn('sortThHtml("y_path", "score_path")', ui_js)
        self.assertIn("resolvePathScore", ui_js)
        self.assertIn('data-score-tip="path"', ui_js)
        self.assertIn('saved.key === "score_path"', sort_js)
        self.assertIn("resolvePathScore", sort_js)

    def test_holdings_chg_has_minute_kline_tip(self):
        island_js = self._read("web", "static", "js", "holdings_table_island.js")
        ui_js = self._read("web", "static", "js", "paper", "holdings_ui.js")
        tip_js = self._read("web", "static", "js", "paper", "holding_chg_tip.js")
        paper_js = self._read("web", "static", "js", "paper.js")
        self.assertIn("data-hold-chg-tip", island_js)
        self.assertIn("data-hold-chg-tip", ui_js)
        self.assertIn("wireHoldingsChgTips", tip_js)
        self.assertIn("minuteBarsToKlinePts", tip_js)
        self.assertIn("wireHoldingsChgTips", paper_js)
        self.assertIn('fetch_if_missing: "1"', tip_js)
        self.assertIn('q.set("as_of"', tip_js)
        self.assertIn("/api/watching/minute-tail", tip_js)

    def test_follow_panel_t0_form_defaults(self):
        panel = self._read("web", "static", "partials", "follow_panel.html")
        self.assertIn('class="paper-t0-cfg-block is-sell-then-buy"', panel)
        self.assertIn('class="paper-t0-cfg-block is-buy-then-sell"', panel)
        stb_idx = panel.index('class="paper-t0-cfg-block is-sell-then-buy"')
        bts_idx = panel.index('class="paper-t0-cfg-block is-buy-then-sell"')
        self.assertLess(bts_idx, stb_idx)  # 正T（buy_then_sell）排在反T（sell_then_buy）前
        self.assertIn("<legend>反 T</legend>", panel[stb_idx : stb_idx + 180])
        self.assertIn("<legend>正 T</legend>", panel[bts_idx : bts_idx + 180])
        self.assertIn('value="fixed_sell_then_buy">固定反T<', panel)
        self.assertIn('value="fixed_buy_then_sell">固定正T<', panel)
        table_js = self._read("web", "static", "js", "paper", "t0_table.js")
        self.assertIn('d.direction === "buy_then_sell"', table_js)
        self.assertIn('dir === "sell_then_buy"', table_js)
        self.assertIn('d.direction === "mixed"', table_js)
        self.assertIn("paper-t0-leg-round", table_js)
        self.assertIn("processSlotGroups", table_js)
        self.assertIn("firstFilledSlotRow", table_js)
        self.assertIn("focusedSlotRow", table_js)
        self.assertIn("expandSlotTradeDays", table_js)
        self.assertIn("sortSlotTradeDays", table_js)
        self.assertIn("slotYhat", table_js)
        self.assertIn("slotClock", table_js)
        self.assertIn("paper-t0-slot-cont", table_js)
        self.assertIn("applyTdRowspan", table_js)
        self.assertIn("slotYRealized", table_js)
        self.assertIn("fmtPredRealizedText", table_js)
        self.assertIn("pickTradeRealized", table_js)
        self.assertNotIn("不配全日真实值", table_js)
        self.assertIn("slotFilled(r)", table_js)
        self.assertNotIn('">槽位</th>', table_js)
        self.assertNotIn('class="paper-t0-col-dir', table_js)
        self.assertIn('<th rowspan="2">向</th>', table_js)
        self.assertIn("data-t0-day-detail", table_js)
        self.assertIn("点击展开各轮预估", table_js)
        self.assertNotIn("paper-t0-day-detail-meta", table_js)
        self.assertIn("paper-t0-day-status", table_js)
        self.assertNotIn("day-detail-chart", table_js)
        # 主表头用 )}">… 锚定，避免误匹配展开明细里的 colspan="2">y_τ
        date_th = table_js.find('title="点击日期展开各轮预估">日</th>')
        on_th = table_js.find(')}">y_on</th>')
        nc_th = table_js.find(')}">y_nc</th>')
        eod_th = table_js.find(')}">y_eod</th>')
        tau_th = table_js.find(')}">y_τ</th>')
        trade_th = table_js.find(')}">y_trade</th>')
        process_th = table_js.find('">过程</th>')
        self.assertLess(date_th, on_th)
        self.assertLess(on_th, nc_th)
        self.assertLess(nc_th, eod_th)
        self.assertLess(eod_th, tau_th)
        self.assertGreater(trade_th, 0)
        self.assertLess(trade_th, process_th)
        t0_ui_js = self._read("web", "static", "js", "paper", "t0_ui.js")
        self.assertIn("仅成交槽位", t0_ui_js)
        self.assertIn("slotYhatBit", table_js)
        self.assertIn("buy_fill", table_js)
        self.assertIn("remaskTraceFills", table_js)
        self.assertIn("买/卖=本轮成交", table_js)
        tip_js = self._read("web", "static", "js", "score_tooltip.js")
        self.assertIn('dir === "sell_then_buy" ? "反 T"', tip_js)
        self.assertIn('dir === "buy_then_sell" ? "正 T"', tip_js)
        ui = self._read("web", "static", "js", "paper", "execution_ui.js")
        self.assertIn("`正${tauBts}/反${tauStb}`", ui)
        self.assertIn("`正${pathBts}/反${pathStb}`", ui)
        self.assertIn("`正${fillBts}/反${fillStb}`", ui)
        viz = self._read("web", "static", "js", "paper", "t0_viz.js")
        self.assertIn("正${meta.nBuyThenSell}/反${meta.nSellThenBuy}", viz)
        self.assertIn("skip_scope", viz)
        self.assertIn("skip_round_count", viz)
        report = self._read("web", "static", "js", "paper", "t0_report.js")
        self.assertIn("data.buy_then_sell_pnl", report)
        self.assertIn("fmtT0DirDays", report)
        self.assertIn("buy_then_sell_days", report)
        self.assertIn("mixed_days", report)
        self.assertIn("portrait.by_slot", report)
        self.assertIn("paper-t0-portrait-slot-table", report)
        self.assertIn("分槽位", report)
        self.assertIn("is-portrait", report)
        self.assertIn("n_with_yhat", report)
        self.assertIn("对齐日级", report)
        self.assertIn("buildPortraitSectionHtml", report)
        self.assertIn("paper-t0-portrait-universe", report)
        self.assertIn("paper-t0-portrait-bands", report)
        self.assertIn("eod命中", report)
        self.assertIn("trade命中", report)
        self.assertIn("eod_hit", report)
        self.assertIn("trade_hit", report)
        self.assertIn("有ŷ", report)
        self.assertIn("成/跳", report)
        self.assertIn("by_tau", report)
        self.assertNotIn('name="sell_trigger_pct_long"', panel)
        self.assertIn('name="buy_trigger_pct_sell_then_buy"', panel)
        self.assertIn('name="sell_trigger_pct_buy_then_sell"', panel)
        self.assertNotIn('name="buy_trigger_pct_reverse"', panel)
        self.assertNotIn('name="buy_trigger_pct_buy_then_sell"', panel)
        self.assertNotIn('name="sell_trigger_pct_sell_then_buy"', panel)
        self.assertNotIn('name="min_range_pct_sell_then_buy"', panel)
        self.assertNotIn('name="min_range_pct_buy_then_sell"', panel)
        self.assertIn('name="y_prefix_vs_path_skip"', panel)
        self.assertIn('name="y_prefix_vs_path_mult"', panel)
        self.assertIn("前缀振幅&lt;|path| * 空间裕度", panel)
        self.assertIn('name="fill_mode_sell_then_buy"', panel)
        self.assertIn('name="fill_mode_buy_then_sell"', panel)
        self.assertIn('name="y_tau_enter_sell_then_buy"', panel)
        self.assertIn('name="y_tau_enter_buy_then_sell"', panel)
        self.assertIn('name="y_path_enter_sell_then_buy"', panel)
        self.assertIn('name="y_path_enter_buy_then_sell"', panel)
        self.assertIn('value="1"', panel)
        self.assertIn('name="enabled" checked', panel)
        self.assertIn('name="must_cover_same_day_sell_then_buy"', panel)
        self.assertIn('name="t0_pm_degrade_sell_then_buy"', panel)
        self.assertIn('name="t0_pm_chase_interval_min_sell_then_buy"', panel)
        self.assertIn('name="must_cover_same_day_buy_then_sell" checked', panel)
        self.assertIn('name="t0_pm_degrade_buy_then_sell"', panel)
        self.assertIn('name="t0_pm_chase_interval_min_buy_then_sell"', panel)
        self.assertIn('name="t0_stop_pct_buy_then_sell"', panel)
        self.assertIn('name="t0_stop_pct_sell_then_buy"', panel)
        self.assertIn('name="t0_stop_arm_bars"', panel)
        self.assertIn('name="t0_stop_on_close"', panel)
        self.assertIn("四轮槽位共用这一套买卖/止损", panel)
        self.assertIn("切 20% 仓", panel)
        self.assertIn('name="y_prefix_segment_enabled"', panel)
        self.assertIn('name="y_prefix_segment_enabled_sell_then_buy" checked', panel)
        self.assertIn('name="y_prefix_segment_enabled_buy_then_sell" checked', panel)
        self.assertIn('name="y_prefix_downbar_ratio_sell_then_buy"', panel)
        self.assertIn('name="y_prefix_upbar_ratio_buy_then_sell"', panel)
        self.assertNotIn('name="y_tau_entry_price_mult"', panel)
        self.assertNotIn("τ入场价倍", panel)

    def test_follow_path_matrix_form(self):
        panel = self._read("web", "static", "partials", "follow_panel.html")
        self.assertIn('id="paper-path-matrix-form"', panel)
        self.assertIn('id="follow-path-matrix"', panel)
        self.assertIn("follow-path-matrix-toolbar", panel)
        self.assertIn("follow-path-matrix-footer", panel)
        self.assertIn("follow-path-matrix-actions", panel)
        self.assertNotIn("follow-path-matrix-pipeline", panel)
        self.assertNotIn("follow-path-matrix-flow", panel)
        self.assertIn('id="paper-adjust"', panel)
        self.assertIn('id="paper-strategy-label"', panel)
        self.assertNotIn("follow-path-matrix-details", panel)
        self.assertNotIn("早盘路径择时", panel)
        self.assertNotIn("Execution · L1", panel)
        self.assertNotIn('name="pm_enabled"', panel)
        self.assertIn("follow-path-matrix-roles", panel)
        self.assertIn("follow-path-matrix-viz", panel)
        self.assertIn("follow-path-matrix-box", panel)
        self.assertNotIn("follow-path-matrix-field", panel)
        self.assertNotIn("follow-path-matrix-lambda", panel)
        self.assertNotIn("follow-path-matrix-gate-", panel)
        self.assertNotIn('class="follow-path-matrix-gate"', panel)
        self.assertNotIn("follow-path-matrix-grid", panel)
        self.assertIn('data-panel="mode"', panel)
        self.assertIn('data-panel="path"', panel)
        self.assertIn('data-panel="on"', panel)
        self.assertIn('data-panel="gates"', panel)
        self.assertNotIn('name="pm_mode"', panel)
        self.assertNotIn("线性对照", panel)
        self.assertIn('name="pm_path_enter"', panel)
        self.assertIn('name="pm_y_on_allow"', panel)
        self.assertIn('name="pm_fusion_w_trade"', panel)
        self.assertIn('name="pm_fusion_w_nc"', panel)
        self.assertIn('name="pm_require_path_on"', panel)
        self.assertNotIn('name="pm_require_nowcast"', panel)
        exe_ui = self._read("web", "static", "js", "paper", "execution_ui.js")
        self.assertIn("enabled: true", exe_ui)
        self.assertNotIn("pm_enabled", exe_ui)
        self.assertIn("syncPathMatrixViz", exe_ui)
        paper = self._read("web", "static", "js", "paper.js")
        self.assertIn("collectPathMatrixForm", paper)

    def test_t0_process_tip_has_kline_helpers(self):
        table = self._read("web", "static", "js", "paper", "t0_table.js")
        paper = self._read("web", "static", "js", "paper.js")
        css = self._read("web", "static", "css", "follow.css")
        self.assertIn("data-t0-process-tip", table)
        self.assertIn("miniKlineSvgFromBars", table)
        self.assertIn("wireT0ProcessTips", table)
        self.assertIn("wireT0ProcessTips", paper)
        self.assertIn("data-t0-day-detail", table)
        self.assertIn("bindT0DayDetailExpand", table)
        self.assertIn("buildDayDetailPayload", table)
        self.assertIn("paper-t0-day-detail", table)
        self.assertIn("paper-t0-process-tip", css)
        self.assertIn("paper-t0-process-kline", css)
        self.assertIn("paper-t0-day-detail", css)
        self.assertIn("paper-t0-day-yhat", css)
        self.assertNotIn("paper-t0-day-detail-meta", css)
        self.assertIn("paper-t0-day-status", css)
        self.assertNotIn("paper-t0-day-detail-chart", css)
        self.assertIn("pickDetailDays", table)
        self.assertNotIn("includeSkippedGateTrace", table)
        self.assertIn("out[loI][5]", table)
        self.assertIn("out[hiI][5]", table)
        self.assertIn(">L</text>", table)
        self.assertIn(">H</text>", table)
        self.assertNotIn("ensureT0GateTraceBindings", table)
        self.assertNotIn("点击展开前向门禁", table)
        self.assertNotIn("paper-t0-row-gate-expandable", css)

    def test_execution_ui_fill_form_sets_checkbox_false(self):
        ui = self._read("web", "static", "js", "paper", "execution_ui.js")
        self.assertIn('if (el.type === "checkbox")', ui)
        self.assertIn("el.checked = !!val", ui)
        self.assertIn('set("enabled", t0.enabled !== false)', ui)
        self.assertIn('t0_ratio: 1.0', ui)
        self.assertIn('specKpi("启用", enabledLbl', ui)

    def test_t0_viz_contrib_main_cause_and_attr(self):
        viz = self._read("web", "static", "js", "paper", "t0_viz.js")
        table = self._read("web", "static", "js", "paper", "t0_table.js")
        css = self._read("web", "static", "css", "follow.css")
        paper_js = self._read("web", "static", "js", "paper.js")
        self.assertIn("renderContribSection", viz)
        self.assertIn("paper-t0-viz-pnl-bar", viz)
        self.assertIn("buildSkipTipHtml", viz)
        self.assertIn("wireT0SkipTips", viz)
        self.assertIn("data-skip-tip", viz)
        self.assertIn("wireT0SkipTips", paper_js)
        self.assertIn("leg.skip_reason || leg.note", paper_js)
        self.assertIn("涨停买不到、跌停卖不出、停牌则跳过并留单", paper_js)
        self.assertIn("意向价与现价中点", paper_js)
        self.assertIn("14:50", paper_js)
        self.assertIn("eod_tau_disagree", viz)
        self.assertIn("y_eod_flat", viz)
        self.assertIn("eod_tau_disagree", table)
        self.assertIn("SKIP_CAT_TIP", table)
        self.assertIn(".paper-t0-viz-contrib-meta", css)
        self.assertIn(".paper-t0-viz-contrib-hint", css)
        self.assertIn(".paper-t0-skip-tip", css)
        self.assertIn(".paper-t0-skip-tip-inner", css)
        # 已撤：归因/分票 PnL 增补图
        self.assertNotIn('data-viz="stockpnl"', viz)
        self.assertNotIn('data-viz="tauattr"', viz)
        self.assertNotIn("drawAttrPnlBars", viz)
        self.assertNotIn("drawStockContribBars", viz)

    def test_follow_panel_target_price_ratio_controls(self):
        panel = self._read("web", "static", "partials", "follow_panel.html")
        ui = self._read("web", "static", "js", "paper", "execution_ui.js")
        self.assertIn('name="y_ratio_cut"', panel)
        self.assertIn('name="y_ratio_boost_cap"', panel)
        self.assertIn("目标弱%", panel)
        self.assertIn("目标强%", panel)
        self.assertIn("y_ratio_boost_cap", ui)
        self.assertIn('set("y_prefix_segment_enabled_sell_then_buy"', ui)
        self.assertIn('y_prefix_segment_enabled_buy_then_sell', ui)
        self.assertIn('y_prefix_upbar_ratio_buy_then_sell', ui)
        self.assertIn('y_prefix_downbar_ratio_sell_then_buy', ui)
        self.assertNotIn("y_tau_entry_price_mult", ui)

    def test_interpret_request_has_offline(self):
        try:
            from web.schemas import QuantInterpretRequest
        except ImportError:
            self.skipTest("fastapi/pydantic not installed")
        self.assertIn("offline", QuantInterpretRequest.model_fields)

    def test_score_review_ui_removed_shadow_strips_on_tau(self):
        panel = self._read("web", "static", "partials", "quant_panel.html")
        review_js = self._read("web", "static", "js", "quant", "domain_score_review.js")
        self.assertNotIn('id="quant-section-score-review"', panel)
        self.assertNotIn("冻结打分", panel)
        self.assertNotIn("双层 ŷ 复盘", panel)
        self.assertNotIn('id="quant-tau-shadow"', panel)
        self.assertNotIn('id="quant-nowcast-shadow"', panel)
        self.assertIn('id="quant-yhat-residual-shadow"', panel)
        self.assertIn('id="quant-excess-mode-shadow"', panel)
        self.assertNotIn("/api/quant/score-review/tau-shadow", review_js)
        self.assertNotIn("/api/quant/score-review/nowcast-shadow", review_js)
        self.assertNotIn("tau_sign_hit_rate", review_js)
        self.assertNotIn("syncOverviewFromTauShadow", review_js)
        self.assertNotIn("refreshShadowReviews", review_js)

        quant_js = self._read("web", "static", "js", "quant.js")
        self.assertNotIn("tau_shadow 覆盖", quant_js)
        self.assertNotIn("盖住复盘 tau_shadow", quant_js)
        self.assertNotIn("/api/quant/score-review?", review_js)
        self.assertNotIn("/api/quant/score-review/dates", review_js)
        self.assertNotIn("/api/quant/score-review/hit-series", review_js)
        self.assertNotIn("/api/quant/score-ledger/freeze", review_js)
        self.assertNotIn("/api/quant/score-ledger/stock-panel", review_js)
        self.assertNotIn("/api/quant/score-ledger/delete", review_js)
        self.assertNotIn("/api/quant/score-outcomes/fill", review_js)
        self.assertNotIn("quant-score-review-run", review_js)

        watching = self._read("web", "static", "js", "quant", "domain_watching.js")
        self.assertIn("/api/quant/score-ledger/series", watching)
        self.assertNotIn("/api/quant/score-ledger/stock-panel", watching)
        self.assertNotIn("/api/quant/score-ledger/freeze", watching)

        viz = self._read("web", "static", "js", "quant", "yhat_viz.js")
        css = self._read("web", "static", "css", "quant.css")
        self.assertNotIn("paintHitSparkline", viz)
        self.assertNotIn("quant-score-review-table", css)
        self.assertNotIn("quant-score-ledger-chip", css)
        self.assertNotIn("#quant-score-review-panel-wrap", css)
        self.assertNotIn("#quant-section-score-review", css)
        self.assertNotIn(".quant-score-review-tau", css)
        self.assertNotIn(".quant-tau-strip", css)

    def test_score_calibration_ui_removed(self):
        panel = self._read("web", "static", "partials", "quant_panel.html")
        review_js = self._read("web", "static", "js", "quant", "domain_score_review.js")
        self.assertNotIn('id="quant-section-score-cal"', panel)
        self.assertNotIn("拟合校准", panel)
        self.assertNotIn("校准 g(ŷ)", panel)
        self.assertNotIn("/api/quant/score-calibration/", review_js)
        self.assertNotIn("refreshCalibrationPanel", review_js)
        self.assertNotIn("quant-score-cal-fit", review_js)

        viz = self._read("web", "static", "js", "quant", "yhat_viz.js")
        tip = self._read("web", "static", "js", "score_tooltip.js")
        fmt = self._read("web", "static", "js", "paper", "fmt.js")
        self.assertNotIn("mountCalibrationCurve", viz)
        self.assertNotIn("paintCalibrationCurve", viz)
        self.assertNotIn("formatCalibrationSection", tip)
        self.assertNotIn("resolveCalTradeScore", fmt)
        self.assertNotIn("watching-score-cal", tip)


if __name__ == "__main__":
    unittest.main()
