"""量化前端关键字符串守卫（指向 quant.js / partials，不再读已拆空的 index.html/app.js）。"""

import os
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)


class TestWebQuantJsGuards(unittest.TestCase):
    def _read(self, *parts):
        path = os.path.join(ROOT, *parts)
        with open(path, encoding="utf-8") as f:
            return f.read()

    def test_quant_js_neutral_compare_and_export(self):
        js = self._read("web", "static", "js", "quant.js")
        export_js = self._read("web", "static", "js", "quant", "domain_export.js")
        self.assertIn("QUANT_EXPORT_PRESETS", js)
        self.assertIn("初始 50 万 · 现金地板 10 万", js)
        self.assertNotIn("初始 100 万 · 现金地板 50 万", js)
        self.assertIn('previewQuantExport("markdown")', js)
        self.assertIn("runQuantInterpret", js)
        self.assertIn("forceOffline: true", js)
        self.assertIn("llmAvailable", export_js)
        self.assertIn("offline: useOffline", export_js)
        self.assertIn("readDailyBtOverrides", export_js)
        self.assertIn("quant_daily_bt_opts_v5", export_js)
        self.assertIn("quant-daily-on-alpha", export_js)
        self.assertIn("quant-daily-rank-enter", export_js)
        self.assertIn("quant-daily-rank-strong", export_js)
        self.assertIn("restoreLastPortfolioBacktest", js)
        self.assertIn('page === "replay"', js)

    def test_tau_coef_formula_compact_js(self):
        ic = self._read("web", "static", "js", "quant", "factor_ic_ui.js")
        quant_js = self._read("web", "static", "js", "quant.js")
        css = self._read("web", "static", "css", "quant.css")
        self.assertIn("compactYSpecFormula", ic)
        self.assertIn("pickTauAnchorKeys", ic)
        self.assertIn("quant-rem-coef-tau-spark", ic)
        self.assertIn("quant-rem-coef-spec-metrics", ic)
        self.assertIn("OOS · τ", ic)
        self.assertIn("complexity_lag1", ic)
        self.assertIn("complexity_ma5", ic)
        self.assertIn("tpd_lag1", ic)
        self.assertIn("tpd_ma5", ic)
        self.assertIn("canonLagFeatName", ic)
        self.assertIn("complexity_tpd_lag1", ic)
        self.assertIn("cx_lag1", ic)
        self.assertIn("tau_lag1", ic)
        self.assertIn("tau_ma5", ic)
        self.assertIn("t_hi_frac", ic)
        self.assertIn("t_lo_frac", ic)
        self.assertIn("全面板完整行", ic)
        self.assertIn("面板 n", ic)
        self.assertIn('kind = "历史"', ic)
        self.assertIn("PIT 历史真实标签（不含当日）", ic)
        self.assertIn("· 历史 ${histN}", ic)
        self.assertIn("未入模：", ic)
        self.assertIn("5m τ", ic)
        self.assertIn("factor_ic_ui.js?v=${encodeURIComponent(_QV)}", quant_js)
        self.assertNotIn("factor_ic_ui.js?v=p", quant_js)
        self.assertIn("quant-rem-coef-spec-span", css)
        self.assertIn("quant-rem-coef-spec-metrics", css)

    def test_tau_ridge_fit_chip_is_fitted(self):
        quant_js = self._read("web", "static", "js", "quant.js")
        tau_run = quant_js.split("async function runTauRidge")[1].split(
            "async function runOnRidge"
        )[0]
        self.assertIn('chip: "已拟合"', tau_run)
        self.assertNotIn('chip: "未写盘"', tau_run)
        status_fn = quant_js.split("quant-tau-ridge-status")[1][:2200]
        self.assertIn('data.shadow ? "已拟合" : "已启用"', status_fn)

    def test_daily_bt_option_js(self):
        export_js = self._read("web", "static", "js", "quant", "domain_export.js")
        self.assertIn("readDailyBtOverrides", export_js)
        self.assertIn("{ preset, ...readDailyBtOverrides() }", export_js)
        self.assertIn("quant-daily-on-alpha", export_js)
        self.assertIn("readDailyYOnAlpha", export_js)
        self.assertIn("readDailyRankThresholds", export_js)
        self.assertIn("rankPctToScore", export_js)
        self.assertIn("rankScoreToPct", export_js)
        self.assertIn("RANK_PCT_DEFAULT = 1.2", export_js)

    def test_partials_have_key_controls(self):
        panel = self._read("web", "static", "partials", "quant_panel.html")
        self.assertIn('id="quant-daily-fold"', panel)
        self.assertIn('id="quant-daily-on-alpha"', panel)
        self.assertIn('id="quant-daily-rank-enter"', panel)
        self.assertIn('id="quant-daily-rank-strong"', panel)
        self.assertIn("Rank入场%", panel)
        self.assertIn("Rank强%", panel)
        self.assertIn(
            'id="quant-daily-rank-enter" type="number" min="0" max="10" step="0.1" value="1.2"',
            panel,
        )
        self.assertIn(
            'id="quant-daily-rank-strong" type="number" min="0" max="10" step="0.1" value="1.2"',
            panel,
        )
        self.assertIn('id="quant-daily-lookback"', panel)
        self.assertIn('<option value="30" selected>30</option>', panel)
        self.assertIn('<option value="60">60</option>', panel)
        self.assertIn('<option value="90">90</option>', panel)
        self.assertIn("日报历史回测配置", panel)
        self.assertNotIn('id="quant-daily-top-k"', panel)
        self.assertNotIn('id="quant-daily-horizon"', panel)
        self.assertIn("quant-interpret-offline", panel)
        self.assertIn("规则解读", panel)
        self.assertIn("quant-interpret-neutral", panel)
        self.assertIn("quant-ols-run", panel)
        self.assertIn("quant-ols-code", panel)
        self.assertIn("quant-probe-picker", panel)
        self.assertIn("quant-ols-code-menu", panel)
        self.assertIn("quant-probe-run", panel)
        self.assertIn("quant-global-fold", panel)
        self.assertIn("quant-section-threshold", panel)
        self.assertIn("quant-threshold-apply", panel)
        self.assertIn("quant-section-cross", panel)
        self.assertIn("对照验证", panel)
        self.assertIn("quant-ols-summary", panel)
        self.assertIn("quant-factor-list", panel)
        self.assertIn("quant-ridge-lambda", panel)
        self.assertIn("quant-cross-list", panel)
        self.assertIn("quant-weight-table-wrap", panel)
        self.assertIn("quant-cross-run", panel)

        self.assertIn('id="quant-section-minute"', panel)
        self.assertIn('id="quant-cluster-minute-refresh"', panel)
        self.assertIn('id="quant-cluster-minute-topup"', panel)
        self.assertIn("强更 5m", panel)
        self.assertIn("增量补齐", panel)
        self.assertIn('id="quant-cluster-bars-topup"', panel)
        self.assertIn("强更日 K", panel)
        self.assertIn('id="quant-cluster-bars-strip"', panel)
        self.assertIn("quant-cluster-bars-strip quant-bars-desk-status quant-card-head-status is-busy", panel)
        self.assertIn("quant-cluster-bars-strip.is-busy .quant-cluster-bars-msg::before", self._read("web", "static", "css", "base.css"))
        minute_js = self._read("web", "static", "js", "quant", "cluster_minute_ui.js")
        self.assertIn("installClusterMinuteUi", minute_js)
        self.assertIn("/api/quant/cluster-minute/status", minute_js)
        self.assertIn("/api/jobs/cluster-minute-refresh", minute_js)
        self.assertIn('mode: modeS', minute_js)
        self.assertIn("startTopup", minute_js)
        self.assertIn("unwrapJobSnap", minute_js)
        self.assertIn("applyJobFailure", minute_js)
        self.assertIn("syncJobSlot", minute_js)
        bars_js = self._read("web", "static", "js", "quant", "cluster_bars_ui.js")
        self.assertIn("unwrapJobSnap", bars_js)
        self.assertIn("syncJobSlot", bars_js)
        self.assertIn("applyJobFailure", bars_js)
        self.assertIn("startTopup", bars_js)
        self.assertIn('mode: modeS', bars_js)
        self.assertIn("quant-cluster-bars-topup", bars_js)
        self.assertIn("Number(done) > 0", bars_js)
        self.assertIn("if (!inflight && !jobFailure && !jobSuccess && jobSt !== \"running\")", bars_js)
        self.assertIn("if (!inflight && !jobFailure && !jobSuccess && jobSt !== \"running\")", minute_js)
        job_js = self._read("web", "static", "js", "quant", "cluster_job_ui.js")
        self.assertIn("unwrapJobSnap", job_js)
        quant_js = self._read("web", "static", "js", "quant.js")
        self.assertIn("installClusterMinuteUi", quant_js)
        self.assertIn("/api/quant/cx-ridge", quant_js)
        self.assertIn("ridgeFitNBits", quant_js)
        self.assertIn("面板 n=", quant_js)
        self.assertIn("入模 n=", quant_js)
        self.assertIn("quant-cx-ridge-run", panel)
        self.assertIn("quant-section-cx", panel)
        self.assertIn("ŷ_complexity", panel)
        self.assertIn("1 − D/L", panel)
        self.assertIn("complexity_lag1", panel)
        self.assertIn("complexity_ma5", panel)
        self.assertIn("90/10", panel)
        self.assertIn("/api/quant/tpd-ridge", quant_js)
        self.assertIn("quant-tpd-ridge-run", panel)
        self.assertIn("quant-section-tpd", panel)
        self.assertIn("ŷ_tpd", panel)
        self.assertIn("tpd_lag1", panel)
        self.assertIn("tpd_ma5", panel)
        self.assertIn("complexity_tpd_lag1", panel)
        self.assertIn("y_tpd_max", panel)
        self.assertNotIn('name="y_tpd_max"', panel)
        self.assertNotIn("默认 0.40", panel)
        self.assertIn("y_complexity_max", panel)
        self.assertIn("tau_lag1", panel)
        self.assertIn("tau_ma5", panel)
        self.assertIn("path_lag1", panel)
        self.assertIn("path_ma5", panel)
        self.assertNotIn("(1 − D/L)×100", panel)
        self.assertNotIn("/api/quant/r-ridge", quant_js)
        self.assertNotIn("quant-r-ridge-run", panel)
        self.assertNotIn("quant-section-r", panel)
        self.assertNotIn("ŷ_r", panel)

        watching = self._read("web", "static", "partials", "watching_panel.html")
        self.assertIn('id="watching-data-offline"', watching)
        self.assertIn("仅本地仓", watching)
        self.assertIn(
            "data_offline.js",
            self._read("web", "static", "js", "quant", "domain_watching.js"),
        )
        self.assertIn(
            "data_warehouse_topup.js",
            self._read("web", "static", "js", "quant", "domain_watching.js"),
        )
        self.assertIn(
            "ensureWarehouseTopup",
            self._read("web", "static", "js", "quant", "domain_watching.js"),
        )
        self.assertIn(
            "offlineOnlyQuery",
            self._read("web", "static", "js", "quant", "domain_watching.js"),
        )
        offline_js = self._read("web", "static", "js", "data_offline.js")
        self.assertIn('return "offline_only=1"', offline_js)
        self.assertIn("增量补齐", offline_js)
        topup_js = self._read("web", "static", "js", "data_warehouse_topup.js")
        self.assertIn("ensureWarehouseTopup", topup_js)
        self.assertIn("/api/quant/cluster-bars/refresh", topup_js)
        self.assertIn("/api/quant/cluster-minute/refresh", topup_js)
        self.assertIn('mode: "topup"', topup_js)
        follow = self._read("web", "static", "partials", "follow_panel.html")
        self.assertIn('id="follow-data-offline"', follow)
        paper_js = self._read("web", "static", "js", "paper.js")
        self.assertIn("offlineOnlyQuery", paper_js)
        self.assertIn("installDataOfflineToggle", paper_js)
        self.assertIn("ensureWarehouseTopup", paper_js)
        self.assertIn("bindHost", paper_js)
        self.assertIn("fetchHoldingScoresWithRetry", paper_js)
        self.assertIn("applyHoldingsScorePack", paper_js)
        tip_js = self._read("web", "static", "js", "score_tooltip.js")
        self.assertIn("attachDismiss(tip, anchor", tip_js)
        hold_tip_js = self._read("web", "static", "js", "paper", "holding_chg_tip.js")
        self.assertIn("data-hold-chg-code", hold_tip_js)
        rb = self._read("web", "static", "js", "paper", "cluster_rebalance.js")
        self.assertIn("offline_only: true", rb)
        self.assertIn("ensureWarehouseTopup", rb)
        self.assertIn("getDataOfflineOnly", rb)

        replay = self._read("web", "static", "partials", "replay_panel.html")
        self.assertNotIn("quant-neutral-compare-table", replay)
        self.assertNotIn("quant-portfolio-compare", replay)
        self.assertNotIn("quant-return-model-fit", replay)
        self.assertNotIn("quant-research-export", replay)
        self.assertNotIn("quant-backtest-report-export", replay)
        self.assertNotIn("quant-bt-metrics", replay)
        self.assertNotIn("研究池：—", replay)
        self.assertIn("观察池：—", replay)
        self.assertIn('id="replay-pool-meta"', replay)
        self.assertNotIn("replay-card-head", replay)
        self.assertIn('id="replay-kpi-row"', replay)
        self.assertIn('id="replay-kpi-return"', replay)
        self.assertNotIn('id="quant-bt-engine"', replay)
        self.assertNotIn('id="quant-horizon"', replay)
        self.assertNotIn('id="quant-weight-mode"', replay)
        self.assertNotIn('id="quant-dropout-n"', replay)
        self.assertNotIn("研究 Top-K</option>", replay)
        self.assertNotIn(">Horizon</span>", replay)
        self.assertNotIn(">Top K</span>", replay)
        self.assertNotIn('id="quant-top-k"', replay)
        self.assertIn("quant-bt-trades", replay)
        self.assertNotIn("quant-bt-daily", replay)
        self.assertNotIn("quant-bt-holdings-end", replay)
        self.assertIn("横轴全部交易日", replay)
        self.assertIn("悬停看净值与个股明细", replay)
        self.assertNotIn("横轴近15日", replay)
        self.assertNotIn("quant-exclude-st", replay)
        self.assertNotIn("剔 ST", replay)
        self.assertNotIn("replay-oos-band", replay)
        self.assertNotIn("额分位不过滤", replay)
        self.assertNotIn("quant-robustness", replay)
        self.assertNotIn("quant-fit-gap", replay)
        self.assertNotIn("quant-universe-panel", replay)
        self.assertNotIn("quant-score-ic", replay)
        self.assertNotIn("有票后点「跑回测」", replay)
        self.assertIn('id="quant-lookback"', replay)
        self.assertIn('min="10" max="500" value="30"', replay)
        self.assertNotIn('min="30" max="500" value="30"', replay)
        self.assertIn('id="quant-on-alpha"', replay)
        self.assertIn('min="0" max="1" step="0.1" value="0"', replay)
        self.assertIn("ON_Alpha", replay)
        self.assertIn("replay-on-alpha-field", replay)
        self.assertIn('id="quant-w-trade"', replay)
        self.assertIn('id="quant-w-nowcast"', replay)
        self.assertIn("W_TRADE", replay)
        self.assertIn("W_NOWCAST", replay)
        self.assertIn('id="quant-w-trade" type="number" min="0" max="1" step="0.1" value="0.6"', replay)
        self.assertIn('id="quant-w-nowcast" type="number" min="0" max="1" step="0.1" value="0.4"', replay)
        self.assertIn("replay-fusion-field", replay)
        self.assertIn('id="quant-rank-enter"', replay)
        self.assertIn('id="quant-rank-strong"', replay)
        self.assertIn("Rank入场%", replay)
        self.assertIn("Rank强%", replay)
        self.assertIn("replay-rank-field", replay)
        self.assertIn('id="quant-rank-enter" type="number" min="0" max="10" step="0.1" value="1.2"', replay)
        self.assertIn('id="quant-rank-strong" type="number" min="0" max="10" step="0.1" value="1.2"', replay)
        self.assertNotIn('id="quant-rank-enter" type="number" min="0" max="1"', replay)
        self.assertIn("09:30 · 50万 / 地板10万", replay)
        self.assertIn("现金地板 10 万", replay)
        self.assertIn("初始资金 50 万", replay)
        self.assertIn("replay-run-head", replay)
        self.assertIn("replay-lookback-field", replay)
        self.assertNotIn("replay-control-band", replay)
        self.assertIn("1000/2000 股", replay)
        self.assertNotIn("100/200 股", replay)
        self.assertNotIn("初始 100 万 · 地板 50 万", replay)
        self.assertNotIn("09:30 · 100万 / 地板50万", replay)
        self.assertNotIn("回测怎么跑", replay)
        self.assertNotIn("replay-section-howto", replay)
        self.assertNotIn("replay-section-grid", replay)
        self.assertNotIn('id="param-grid"', replay)
        self.assertNotIn("quant-param-grid-run", replay)
        self.assertNotIn("replay-section-cross-title", replay)
        self.assertNotIn("quant-fold-cross", replay)
        self.assertNotIn(">额分位</span>", replay)
        self.assertNotIn(">基准</span>", replay)
        self.assertNotIn("拟合ŷ模型", replay)
        self.assertNotIn("中性化对照", replay)
        self.assertNotIn("导出研究包", replay)
        self.assertNotIn('href="#quant-bt-metrics"', replay)
        self.assertIn('href="#quant-portfolio-chart"', replay)
        bt_js = self._read("web", "static", "js", "quant", "domain_backtest.js")
        self.assertNotIn("param_grid_ui", bt_js)
        self.assertNotIn("/api/quant/param-grid", bt_js)
        self.assertNotIn("/api/quant/portfolio-neutral-compare", bt_js)
        self.assertNotIn("runPortfolioNeutralCompare", bt_js)
        self.assertNotIn("runParamGrid", bt_js)
        quant_js = self._read("web", "static", "js", "quant.js")
        self.assertNotIn("param_grid_ui", quant_js)
        self.assertNotIn("/api/quant/param-grid", quant_js)
        self.assertNotIn("quant-param-grid-run", quant_js)
        self.assertNotIn("lastParamGrid", quant_js)
        self.assertNotIn("topk_research", bt_js)
        self.assertIn("rank_lots", bt_js)
        self.assertNotIn('engine: "paper_replay"', bt_js)
        self.assertNotIn("include_wf_slices", bt_js)
        self.assertIn("y_on_alpha", bt_js)
        self.assertIn("readYOnAlpha", bt_js)
        self.assertIn("readFusionWeights", bt_js)
        self.assertIn("quant-on-alpha", bt_js)
        self.assertIn("quant-w-trade", bt_js)
        self.assertIn("quant-w-nowcast", bt_js)
        self.assertIn("fusion_w_trade", bt_js)
        self.assertIn("fusion_w_nowcast", bt_js)
        self.assertIn("readRankThresholds", bt_js)
        self.assertIn("Math.max(10, Math.min(500, Math.round(n)))", bt_js)
        self.assertNotIn("Math.max(30, Math.min(500, Math.round(n)))", bt_js)
        self.assertIn("rankPctToScore", bt_js)
        self.assertIn("RANK_PCT_DEFAULT = 1.2", bt_js)
        self.assertIn("pct / 100", bt_js)
        self.assertIn("rank_enter", bt_js)
        self.assertIn("rank_strong", bt_js)
        self.assertIn("quant-rank-enter", bt_js)
        self.assertIn("quant-rank-strong", bt_js)
        self.assertIn("include_benchmark: true", bt_js)
        self.assertNotIn("quant-top-k", bt_js)
        self.assertIn("isReplayDesk", bt_js)
        self.assertIn("writePortfolioSummary", bt_js)
        self.assertIn("buildDayDetailsMap", bt_js)
        self.assertIn("dayDetails: buildDayDetailsMap(windowed)", bt_js)
        self.assertIn("nameByCode: state.watchingNameByCode", bt_js)
        result_js = self._read("web", "static", "js", "quant", "bt_result.js")
        self.assertIn("trade_days", result_js)
        self.assertIn("request?.lookback", result_js)
        self.assertIn('label: "交易日"', result_js)
        self.assertNotIn("共同交易日", result_js)
        lw_js = self._read("web", "static", "js", "lw_charts.js")
        self.assertIn("lw-hover-tip-legs", lw_js)
        self.assertIn("renderDayLegRows", lw_js)
        self.assertIn("开盘清仓，涨跌仅隔夜", lw_js)
        self.assertIn("持有段：清仓=隔夜", lw_js)
        self.assertIn("legDisplayName", lw_js)
        self.assertIn("nameByCode", lw_js)
        self.assertIn("dayDetails", lw_js)
        self.assertIn('fit: "host"', bt_js)
        self.assertIn("shrinkTracks: false", bt_js)
        self.assertIn("rowHeight: 48", bt_js)
        self.assertIn("virtual_table.js?v=${encodeURIComponent(_V)}", bt_js)
        snap_fn = bt_js[bt_js.find("async function loadLastBacktestSnapshot()") :]
        self.assertIn("if (isReplayDesk()) return", snap_fn[:120])
        self.assertIn("async function restoreLastPortfolioBacktest()", bt_js)
        self.assertIn("/api/quant/last-portfolio-backtest", bt_js)
        self.assertIn("function applyPortfolioBtParams(req)", bt_js)
        self.assertIn("上次结果", bt_js)
        self.assertIn("function frozenBtCaliber(ps)", bt_js)
        self.assertIn("frozenBtCaliber(ps)", bt_js)
        self.assertNotIn("K${ps.params?.top_k", bt_js)
        self.assertNotIn("renderDailyNavTable", bt_js)
        self.assertNotIn("renderHoldingsEnd", bt_js)
        trades_js = self._read("web", "static", "js", "quant", "bt_trades.js")
        self.assertIn("BT_LEDGER_TRADE_COLS", trades_js)
        self.assertIn('kind: "day"', trades_js)
        self.assertIn("bt-ledger-day", trades_js)
        self.assertIn("bt-stack-score", trades_js)
        self.assertIn("bt-ledger-day-cash", trades_js)
        self.assertIn("`净值 ${d.equityText}`", trades_js)
        self.assertNotIn("_stackLegHtml", trades_js)
        self.assertNotIn("bt-stack-leg", trades_js)
        self.assertNotIn("bt-stack-parts", trades_js)
        self.assertNotIn("bt-stack-top", trades_js)
        self.assertNotIn("bt-pair-sep", trades_js)
        self.assertNotIn("bt-stack-v", trades_js)
        self.assertNotIn("y_tradeText", trades_js)
        self.assertNotIn("y_nowcastText", trades_js)
        self.assertNotIn("rowHeight: 58", bt_js)
        trades_css = self._read("web", "static", "css", "quant.css")
        self.assertNotIn("bt-stack-leg", trades_css)
        self.assertNotIn("bt-stack-parts", trades_css)
        self.assertNotIn("bt-stack-top", trades_css)
        self.assertNotIn("bt-pair-sep", trades_css)
        self.assertNotIn(".bt-trade-side", trades_css)
        self.assertIn("realized_cc", trades_js)
        self.assertIn("realized_on", trades_js)
        self.assertIn('id: "y_on"', trades_js)
        self.assertIn('id: "y_tau"', trades_js)
        self.assertIn('label: "y_τ"', trades_js)
        self.assertIn("realized_tau", trades_js)
        self.assertIn("bt-pair-real", trades_js)
        self.assertIn("预估(真实)", trades_js)
        self.assertIn("widthMin: \"8.8rem\"", trades_js)
        self.assertNotIn(">实</span>", trades_js)
        self.assertNotIn("bt-real", trades_js)
        self.assertNotIn('id: "y_trade"', trades_js)
        self.assertNotIn('id: "y_nowcast"', trades_js)
        self.assertIn('if (v == null || v === "") return null;', trades_js)
        self.assertIn("isRankLotsLedger", trades_js)
        self.assertNotIn("rank_lots 成交流水", trades_js)
        self.assertNotIn("同日先卖后买", trades_js)
        self.assertIn('id: "action"', trades_js)
        self.assertIn('id: "open_date"', trades_js)
        self.assertIn('label: "开日日期"', trades_js)
        self.assertNotIn('id: "cost_px"', trades_js)
        self.assertNotIn('label: "成本价"', trades_js)
        self.assertIn('id: "basis"', trades_js)
        self.assertIn('label: "成本"', trades_js)
        self.assertIn("attachLedgerOpenCost", trades_js)
        self.assertIn('id: "cost"', trades_js)
        self.assertIn('label: "成交额"', trades_js)
        self.assertIn("fmtScore(rk * 100", trades_js)
        self.assertIn("展示百分数", trades_js)
        self.assertIn("过 Rank入场%", trades_js)
        self.assertIn("过 Rank强%", trades_js)
        self.assertNotIn("×100%", trades_js)
        self.assertNotIn('id: "reason"', trades_js)
        self.assertNotIn('label: "原因"', trades_js)
        self.assertNotIn('id: "cash"', trades_js)
        self.assertNotIn('id: "rank"', trades_js)
        self.assertNotIn('label: "序"', trades_js)
        self.assertIn("bt-ledger-grid", bt_js)
        self.assertIn('!== "skipped"', bt_js)
        self.assertIn("quant-bt-stock-chip", trades_js)
        self.assertIn("点击看日线", trades_js)
        self.assertIn("btTradeRowAttrs", bt_js)
        self.assertIn("focusBtTradeStock", bt_js)
        self.assertIn("paintStockKline", bt_js)
        self.assertIn("/api/watching/daily-chart", bt_js)
        self.assertIn('"data-code": d.stock_code', bt_js)
        self.assertIn('id="quant-chart-title"', replay)
        self.assertIn('id="quant-chart-nav-mode"', replay)
        replay_py = self._read("core", "backtest", "paper_replay.py")
        self.assertIn("sim_trades", replay_py)
        self.assertIn("overlay_session_day_bars", replay_py)
        self.assertIn("session_overlay", replay_py)
        self.assertNotIn("[-80:]", replay_py)
        self.assertNotIn("rebalance_logs[-40:]", replay_py)

    def test_t0_trade_table_columns_v6(self):
        table_js = self._read("web", "static", "js", "paper", "t0_table.js")
        self.assertNotIn('">y_nc_oc</th>', table_js)
        self.assertNotIn(')}">y_eod</th>', table_js)
        self.assertNotIn(')}">y_trade</th>', table_js)
        self.assertNotIn(')}">y_nowcast</th>', table_js)
        self.assertNotIn("fmtNowcastOcCell", table_js)
        self.assertNotIn("pickTradeRealized", table_js)
        self.assertNotIn("pickNowcastRealized", table_js)
        self.assertIn("tradeSlotPxCells", table_js)
        self.assertIn(')}">y_τ</th>', table_js)
        self.assertIn(')}">y_path</th>', table_js)
        self.assertIn(')}">y_complexity</th>', table_js)
        self.assertIn(')}">y_tpd</th>', table_js)
        css = self._read("web", "static", "css", "follow.css")
        self.assertIn("y_τ | y_path | y_complexity | y_tpd", css)
        tau_rule = css.index("thead th.paper-t0-col-tau")
        path_rule = css.index("thead th.paper-t0-col-path,\n.paper-t0-trades-table tbody td.paper-t0-col-path {\n  border-left:")
        cx_rule = css.index("thead th.paper-t0-col-cx,\n.paper-t0-trades-table tbody td.paper-t0-col-cx {\n  border-left:")
        tpd_rule = css.index("thead th.paper-t0-col-tpd,\n.paper-t0-trades-table tbody td.paper-t0-col-tpd {\n  border-left:")
        self.assertLess(tau_rule, path_rule)
        self.assertLess(path_rule, cx_rule)
        self.assertLess(cx_rule, tpd_rule)
        self.assertIn("function cxMergedCellHtml", table_js)
        self.assertIn("function tpdMergedCellHtml", table_js)
        self.assertNotIn("cxRealizedCellHtml", table_js)
        self.assertIn("cxMergedCellHtml(scoreHost, dayRef || d, slotYRealized)", table_js)
        self.assertIn("tpdMergedCellHtml(scoreHost, dayRef || d, slotYRealized)", table_js)
        self.assertNotIn("paper-t0-col-next", table_js)
        self.assertNotIn(')}">y_next</th>', table_js)
        self.assertNotIn("nextMergedCellHtml", table_js)
        self.assertNotIn("y_use_next", table_js)

    def test_score_tooltip_nc_oc_tip_mode(self):
        tip_js = self._read("web", "static", "js", "score_tooltip.js")
        self.assertIn('tip === "nc_oc"', tip_js)
        self.assertIn("formatNcOcSection", tip_js)
        self.assertIn('tipMode === "nc_oc"', tip_js)

    def test_score_tooltip_path_feat_labels_zh(self):
        tip_js = self._read("web", "static", "js", "score_tooltip.js")
        self.assertIn('ret_open_to_tau: "开盘→τ 收益 %"', tip_js)
        self.assertIn('range_pct: "前缀振幅 %"', tip_js)
        self.assertIn('t_hi_frac: "最高点相对前缀进度"', tip_js)
        self.assertIn('t_hi_frac: "最高点相对前缀进度"', tip_js)
        self.assertIn('pullback_from_high: "自高回撤 %"', tip_js)
        self.assertIn("PATH_FEAT_LABELS[k]", tip_js)
        self.assertIn('key === "path" && k && PATH_FEAT_LABELS[k]', tip_js)

    def test_y_nc_resolve_helpers_remain_in_fmt(self):
        fmt_js = self._read("web", "static", "js", "paper", "fmt.js")
        self.assertIn("resolveNowcastCcScore", fmt_js)
        self.assertIn("resolveNowcastScore(it)", fmt_js)
        self.assertIn("return resolveNowcastCcScore(it)", fmt_js)
        self.assertIn("Y_NC_TITLE", fmt_js)
        self.assertIn("Y_NC_OC_TITLE", fmt_js)
        self.assertIn("Y_COMPLEXITY_TITLE", fmt_js)
        self.assertIn("Y_TPD_TITLE", fmt_js)
        self.assertIn("nowcast = nc", fmt_js)

    def test_follow_panel_nc_terminology(self):
        panel = self._read("web", "static", "partials", "follow_panel.html")
        self.assertNotIn('name="y_block_tau_nowcast_sign"', panel)
        self.assertNotIn('name="y_nowcast_oc_gate"', panel)
        self.assertNotIn("nc闸", panel)
        self.assertNotIn("nowcast OC", panel)

    def test_t0_trades_fullscreen_toggle(self):
        table_js = self._read("web", "static", "js", "paper", "t0_table.js")
        css = self._read("web", "static", "css", "follow.css")
        self.assertIn("data-trades-fs-toggle", table_js)
        self.assertIn("paper-t0-trades-panel", table_js)
        self.assertIn("bindT0TradesFullscreen", table_js)
        self.assertIn(".paper-t0-trades-panel.is-fs", css)

    def test_t0_trade_date_col_fits_iso_day(self):
        table_js = self._read("web", "static", "js", "paper", "t0_table.js")
        css = self._read("web", "static", "css", "follow.css")
        self.assertIn('date: "104px"', table_js)
        self.assertIn('tau: "112px"', table_js)
        self.assertIn('path: "112px"', table_js)
        self.assertIn('cx: "108px"', table_js)
        self.assertIn('tpd: "108px"', table_js)
        self.assertIn('process: "340px"', table_js)
        self.assertIn("fmtTradeDate", table_js)
        self.assertIn("width: 104px", css)
        self.assertIn(".paper-t0-col-tau { width: 112px; min-width: 112px; }", css)
        self.assertIn(".paper-t0-col-path { width: 112px; min-width: 112px; }", css)
        self.assertIn(".paper-t0-col-cx { width: 108px; min-width: 108px; }", css)
        self.assertIn(".paper-t0-col-tpd { width: 108px; min-width: 108px; }", css)
        self.assertIn(".paper-t0-col-date", css)

    def test_live_t0_tables_omit_realized_pair(self):
        table_js = self._read("web", "static", "js", "paper", "t0_table.js")
        ui_js = self._read("web", "static", "js", "paper", "t0_ui.js")
        self.assertIn("fmtPredRealizedText", table_js)
        self.assertIn("showRealized = true", table_js)
        self.assertEqual(ui_js.count("showRealized: false"), 2)

    def test_holdings_table_has_t0_column(self):
        island_js = self._read("web", "static", "js", "holdings_table_island.js")
        badge_js = self._read("web", "static", "js", "paper", "holding_t0_badge.js")
        css = self._read("web", "static", "css", "follow.css")
        self.assertIn('id: "t0"', island_js)
        self.assertIn("holdingT0BadgeHtml", island_js)
        self.assertIn("t0_intraday", island_js)
        self.assertIn("paper-hold-t0-badge", badge_js)
        self.assertIn(".paper-hold-t0-badge", css)

    def test_holdings_table_has_y_path_column(self):
        island_js = self._read("web", "static", "js", "holdings_table_island.js")
        ui_js = self._read("web", "static", "js", "paper", "holdings_ui.js")
        sort_js = self._read("web", "static", "js", "paper", "holdings_sort.js")
        self.assertIn('id: "score_path"', island_js)
        self.assertIn('label: "y_path"', island_js)
        self.assertIn("resolvePathScore", island_js)
        self.assertIn("score_path: \"path\"", island_js)
        self.assertIn('sortThHtml("y_path", "score_path")', ui_js)
        self.assertIn("resolvePathScore", ui_js)
        self.assertIn('data-score-tip="path"', ui_js)
        self.assertIn('saved.key === "score_path"', sort_js)
        self.assertIn("resolvePathScore", sort_js)

    def test_holdings_chg_has_minute_kline_tip(self):
        island_js = self._read("web", "static", "js", "holdings_table_island.js")
        ui_js = self._read("web", "static", "js", "paper", "holdings_ui.js")
        tip_js = self._read("web", "static", "js", "paper", "holding_chg_tip.js")
        paper_js = self._read("web", "static", "js", "paper.js")
        self.assertIn("data-hold-chg-tip", island_js)
        self.assertIn("data-hold-chg-tip", ui_js)
        self.assertIn("wireHoldingsChgTips", tip_js)
        self.assertIn("minuteBarsToKlinePts", tip_js)
        self.assertIn("wireHoldingsChgTips", paper_js)
        self.assertIn('fetch_if_missing: "1"', tip_js)
        self.assertIn('q.set("as_of"', tip_js)
        self.assertIn("/api/watching/minute-tail", tip_js)

    def test_follow_panel_t0_form_defaults(self):
        panel = self._read("web", "static", "partials", "follow_panel.html")
        self.assertIn('class="paper-t0-cfg-block is-sell-then-buy"', panel)
        self.assertIn('class="paper-t0-cfg-block is-buy-then-sell"', panel)
        stb_idx = panel.index('class="paper-t0-cfg-block is-sell-then-buy"')
        bts_idx = panel.index('class="paper-t0-cfg-block is-buy-then-sell"')
        self.assertLess(bts_idx, stb_idx)  # 正T（buy_then_sell）排在反T（sell_then_buy）前
        self.assertIn("<legend>反 T</legend>", panel[stb_idx : stb_idx + 180])
        self.assertIn("<legend>正 T</legend>", panel[bts_idx : bts_idx + 180])
        self.assertIn("选腿仅收盘带宽", panel)
        self.assertIn("第二腿=冻结对侧带", panel)
        table_js = self._read("web", "static", "js", "paper", "t0_table.js")
        self.assertIn('d.direction === "buy_then_sell"', table_js)
        self.assertIn('dir === "sell_then_buy"', table_js)
        self.assertIn('d.direction === "mixed"', table_js)
        self.assertIn("paper-t0-leg-round", table_js)
        self.assertIn("processSlotGroups", table_js)
        self.assertIn("firstFilledSlotRow", table_js)
        self.assertIn("focusedSlotRow", table_js)
        self.assertIn("expandSlotTradeDays", table_js)
        self.assertIn("sortSlotTradeDays", table_js)
        self.assertIn("slotYhat", table_js)
        self.assertIn("predicted_score_complexity", table_js)
        self.assertIn("y_complexity_hat", table_js)
        self.assertIn("predicted_score_cx", table_js)
        self.assertIn("y_cx_hat", table_js)
        self.assertIn("predicted_score_tpd", table_js)
        self.assertIn("y_tpd_hat", table_js)
        self.assertIn("Y_COMPLEXITY_TITLE", table_js)
        self.assertIn("Y_TPD_TITLE", table_js)
        self.assertNotIn("Y_CX_TITLE", table_js)
        self.assertIn("slotGateYTau", table_js)
        self.assertIn("bar_prefix", table_js)
        self.assertIn("tradeScoreHost", table_js)
        self.assertIn("scanRowForHm", table_js)
        self.assertIn("open_anchor", table_js)
        self.assertIn("wireT0DayDebugExpand", table_js)
        self.assertIn("paper-t0-day-debug-toggle", table_js)
        self.assertEqual(table_js.count("function tradeTableColCount"), 1)
        self.assertIn("n += 2; // y_τ y_path", table_js)
        self.assertIn("if (ctx.showRealized) n += 2; // y_complexity y_tpd", table_js)
        self.assertIn("closeBandDayOhlcCheck", table_js)
        self.assertIn("closeBandScanTitleHtml", table_js)
        self.assertIn(">upper</th>", table_js)
        self.assertIn(">lower</th>", table_js)
        self.assertIn("fmtScanPct(r.upper_pct)", table_js)
        self.assertIn("fmtScanPct(r.lower_pct)", table_js)
        self.assertIn("nth-child(n + 8)", self._read("web", "static", "css", "follow.css"))
        self.assertIn("paper-t0-scan-ohlc-check", self._read("web", "static", "css", "follow.css"))
        self.assertIn("slotClock", table_js)
        self.assertIn("paper-t0-slot-cont", table_js)
        self.assertIn("applyTdRowspan", table_js)
        self.assertIn("slotYRealized", table_js)
        self.assertIn("fmtPredRealizedText", table_js)
        self.assertIn("pickTauRealized", table_js)
        self.assertNotIn("pickTradeRealized", table_js)
        self.assertNotIn("不配全日真实值", table_js)
        self.assertIn("slotFilled(r)", table_js)
        self.assertNotIn('">槽位</th>', table_js)
        self.assertNotIn('class="paper-t0-col-dir', table_js)
        self.assertNotIn("data-t0-day-detail", table_js)
        self.assertNotIn("点击展开各轮预估", table_js)
        self.assertNotIn("各轮预估", table_js)
        self.assertNotIn("bindT0DayDetailExpand", table_js)
        self.assertNotIn("buildDayDetailPayload", table_js)
        self.assertNotIn("buildDayDetailHtml", table_js)
        self.assertNotIn("paper-t0-day-detail-meta", table_js)
        self.assertNotIn("paper-t0-day-detail-chart", table_js)
        self.assertNotIn("buildDayDetailOhlcTable", table_js)
        self.assertIn("slotOhlcFromBars", table_js)
        self.assertNotIn("fmtOhlcTd", table_js)
        self.assertNotIn("slotWindowBars", table_js)
        self.assertNotIn("fmtSlotKlineTd", table_js)
        self.assertNotIn("paper-t0-slot-kline", table_js)
        self.assertNotIn("5m×6", table_js)
        # 主表头列序：日 → O/L/H/C/Ĉ_τ/R̂_τ → y_τ → y_path → y_complexity → y_tpd → 过程
        date_th = table_js.find('class="paper-t0-col-date">日</th>')
        o_th = table_js.find('class="paper-t0-col-o num" title="本轮触发根 5m 开盘">O</th>')
        l_th = table_js.find('class="paper-t0-col-l num" title="本轮触发根 5m 最低">L</th>')
        h_th = table_js.find('class="paper-t0-col-h num" title="本轮触发根 5m 最高">H</th>')
        c_th = table_js.find('class="paper-t0-col-c num" title="本轮触发根 5m 收盘">C</th>')
        ctau_th = table_js.find('class="paper-t0-col-ctau num" title="ĉ_τ')
        rtau_th = table_js.find('class="paper-t0-col-rtau num" title="r̂_τ')
        tau_th = table_js.find(')}">y_τ</th>')
        path_th = table_js.find(')}">y_path</th>')
        cx_th = table_js.find('class="paper-t0-col-cx num paper-t0-col-y paper-t0-col-y-cx"')
        tpd_th = table_js.find('class="paper-t0-col-tpd num paper-t0-col-y paper-t0-col-y-tpd"')
        process_th = table_js.find('">过程</th>')
        self.assertNotIn(')}">y_on</th>', table_js)
        self.assertNotIn(')}">y_eod</th>', table_js)
        self.assertNotIn(')}">y_trade</th>', table_js)
        self.assertNotIn(')}">y_nowcast</th>', table_js)
        self.assertNotIn(')}">y_next</th>', table_js)
        self.assertLess(date_th, o_th)
        self.assertLess(o_th, l_th)
        self.assertLess(l_th, h_th)
        self.assertLess(h_th, c_th)
        self.assertLess(c_th, ctau_th)
        self.assertLess(ctau_th, rtau_th)
        self.assertLess(rtau_th, tau_th)
        self.assertLess(tau_th, path_th)
        self.assertLess(path_th, cx_th)
        self.assertLess(cx_th, tpd_th)
        self.assertLess(tpd_th, process_th)
        self.assertIn(">R̂_τ</th>", table_js)
        self.assertIn("paper-t0-rtau-enter", table_js)
        self.assertIn("slotRtauEnterPct", table_js)
        self.assertIn("tradeSlotPxCells", table_js)
        self.assertIn("r_tau_enter", table_js)
        self.assertIn("R入场%", table_js)
        self.assertIn("页面 R入场%", table_js)
        self.assertIn("0–1.0", table_js)
        self.assertNotIn("取更严", table_js)
        self.assertNotIn("入场阈=破带沿", table_js)
        self.assertNotIn("R入场 关", table_js)
        self.assertNotIn("pickNowcastRealized", table_js)
        self.assertNotIn("fmtYhatWithCloseTd", table_js)
        self.assertNotIn('title="ŷ_τ 分数(label)">y_τ</th>', table_js)
        self.assertNotIn('title="主显分钟映后 c_τ；悬停/旁注日原（估空间未÷S）">c_τ</th>', table_js)
        self.assertNotIn('colspan="3">y_τ</th>', table_js)
        t0_ui_js = self._read("web", "static", "js", "paper", "t0_ui.js")
        self.assertIn("仅成交槽位", t0_ui_js)
        self.assertIn("slotYhatBit", table_js)
        self.assertIn("buy_fill", table_js)
        self.assertIn("remaskTraceFills", table_js)
        self.assertIn("买/卖=本轮成交", table_js)
        tip_js = self._read("web", "static", "js", "score_tooltip.js")
        self.assertIn('dir === "sell_then_buy" ? "反 T"', tip_js)
        self.assertIn('dir === "buy_then_sell" ? "正 T"', tip_js)
        ui = self._read("web", "static", "js", "paper", "execution_ui.js")
        self.assertIn('const fillLbl = "trigger"', ui)
        self.assertIn('fill_mode: "trigger"', ui)
        self.assertNotIn("paper-t0-spec-gate-matrix", ui)
        self.assertNotIn("dual_y 准入门槛", ui)
        viz = self._read("web", "static", "js", "paper", "t0_viz.js")
        self.assertIn("正${meta.nBuyThenSell}/反${meta.nSellThenBuy}", viz)
        self.assertIn("skip_scope", viz)
        self.assertIn("skip_round_count", viz)
        report = self._read("web", "static", "js", "paper", "t0_report.js")
        self.assertIn("data.buy_then_sell_pnl", report)
        self.assertIn("fmtT0DirDays", report)
        self.assertIn("buy_then_sell_days", report)
        self.assertIn("mixed_days", report)
        self.assertIn("portrait.by_slot", report)
        self.assertIn("localeCompare", report)
        self.assertIn("paper-t0-portrait-slot-table", report)
        self.assertIn("分槽位", report)
        self.assertIn("is-portrait", report)
        self.assertIn("n_with_yhat", report)
        self.assertIn("对齐日级", report)
        self.assertIn("buildPortraitSectionHtml", report)
        self.assertIn("paper-t0-portrait-universe", report)
        self.assertIn("paper-t0-portrait-bands", report)
        self.assertNotIn("eod命中", report)
        self.assertNotIn("trade命中", report)
        self.assertIn("有ŷ", report)
        self.assertIn("成/跳", report)
        self.assertIn("close_band_scan", report)
        self.assertIn("by_tau", report)
        self.assertNotIn('name="sell_trigger_pct_long"', panel)
        self.assertNotIn('name="buy_trigger_pct_sell_then_buy"', panel)
        self.assertNotIn('name="sell_trigger_pct_buy_then_sell"', panel)
        self.assertNotIn('name="buy_trigger_pct_reverse"', panel)
        self.assertNotIn('name="buy_trigger_pct_buy_then_sell"', panel)
        self.assertNotIn('name="sell_trigger_pct_sell_then_buy"', panel)
        self.assertNotIn('name="min_range_pct_sell_then_buy"', panel)
        self.assertNotIn('name="min_range_pct_buy_then_sell"', panel)
        removed_fields = (
            "y_tau_map",
            "y_trade_enter",
            "y_tau_enter_buy_then_sell",
            "y_tau_entry_price_skip_buy_then_sell",
            "y_tau_exit_price_skip_buy_then_sell",
            "y_gap_tier_mode",
            "y_tau_require_for_leg1",
            "y_ratio_cut",
            "y_ratio_boost_cap",
            "use_atr",
        )
        for name in removed_fields:
            self.assertNotIn(f'name="{name}"', panel, msg=name)
        self.assertNotIn('name="fill_mode_sell_then_buy"', panel)
        self.assertNotIn('name="fill_mode_buy_then_sell"', panel)
        self.assertNotIn('name="y_on_allow"', panel)
        self.assertIn('name="enabled" checked', panel)
        self.assertIn('name="must_cover_same_day_sell_then_buy" checked', panel)
        self.assertIn('name="t0_pm_degrade_sell_then_buy"', panel)
        self.assertIn('name="t0_pm_chase_interval_min_sell_then_buy"', panel)
        self.assertIn('name="must_cover_same_day_buy_then_sell" checked', panel)
        self.assertIn('name="t0_pm_degrade_buy_then_sell"', panel)
        self.assertIn('name="t0_pm_chase_interval_min_buy_then_sell"', panel)
        self.assertIn('name="t0_stop_pct_buy_then_sell"', panel)
        self.assertIn('name="t0_stop_pct_sell_then_buy"', panel)
        self.assertIn('name="t0_stop_arm_bars"', panel)
        self.assertIn('name="t0_stop_on_close"', panel)
        self.assertIn("v6 收盘带宽", panel)
        self.assertIn("每轮 40%", panel)
        self.assertIn("做 T 回测直接读当前表单", panel)
        self.assertNotIn('name="y_prefix_segment_enabled"', panel)
        self.assertNotIn('name="y_prefix_segment_enabled_buy_then_sell"', panel)
        self.assertNotIn('name="y_prefix_segment_enabled_sell_then_buy"', panel)
        self.assertNotIn('name="t0_leg_confirm_mode"', panel)
        self.assertIn('name="t0_close_band_delta_pct"', panel)
        self.assertIn(">超额带宽δ%</span>", panel)
        self.assertNotIn(">带宽δ%</span>", panel)
        self.assertIn('name="t0_price_space_gate"', panel)
        self.assertIn('name="t0_price_space_max_dev_pct"', panel)
        self.assertIn('name="t0_price_space_prev_dev_pct"', panel)
        self.assertIn('name="t0_round_ratio"', panel)
        self.assertIn('name="t0_max_position_pct"', panel)
        self.assertNotIn('name="t0_env_gate_enabled"', panel)
        self.assertNotIn('name="t0_env_one_sided_tau_abs"', panel)
        self.assertNotIn('name="t0_slots_roll_unused"', panel)
        self.assertIn('name="t0_slots_max_rounds"', panel)
        self.assertIn("0=不开第一腿", panel)
        self.assertNotIn('name="t0_slots_enabled"', panel)
        self.assertNotIn('name="y_path_abandon_bars"', panel)
        self.assertNotIn('name="y_path_abandon_enabled"', panel)
        self.assertNotIn('name="t0_confirm_dev_pct"', panel)
        self.assertNotIn('name="t0_env_min_range_pct"', panel)
        self.assertNotIn('name="y_prefix_segment_enabled_sell_then_buy"', panel)
        self.assertNotIn('name="y_prefix_segment_enabled_buy_then_sell"', panel)
        self.assertNotIn('name="y_prefix_downbar_ratio_sell_then_buy"', panel)
        self.assertNotIn('name="y_prefix_upbar_ratio_buy_then_sell"', panel)

    def test_t0_backtest_maps_failed_to_fetch(self):
        paper = self._read("web", "static", "js", "paper.js")
        self.assertIn("t0FetchErrorMessage", paper)
        self.assertIn("failed to fetch", paper)
        self.assertIn("回测连接中断或超时", paper)
        self.assertIn("仅选中", paper)
        self.assertIn("预演连接中断或超时", paper)
        self.assertIn("restoreLastT0Backtest", paper)
        self.assertIn("/api/quant/last-t0-backtest", paper)
        self.assertIn("上次 ${at}", paper)

    def test_follow_path_matrix_form(self):
        panel = self._read("web", "static", "partials", "follow_panel.html")
        self.assertIn('id="paper-path-matrix-form"', panel)
        self.assertIn('id="follow-path-matrix"', panel)
        self.assertIn("follow-path-matrix-toolbar", panel)
        self.assertIn("follow-path-matrix-footer", panel)
        self.assertIn("follow-path-matrix-actions", panel)
        self.assertNotIn("follow-path-matrix-pipeline", panel)
        self.assertNotIn("follow-path-matrix-flow", panel)
        self.assertIn('id="paper-adjust"', panel)
        self.assertIn('id="paper-strategy"', panel)
        self.assertNotIn('id="paper-strategy-label"', panel)
        self.assertNotIn("follow-path-matrix-strategy", panel)
        self.assertNotIn("follow-path-matrix-details", panel)
        self.assertNotIn("早盘路径择时", panel)
        self.assertNotIn("Execution · L1", panel)
        self.assertNotIn('name="pm_enabled"', panel)
        self.assertNotIn("follow-path-matrix-roles", panel)
        self.assertNotIn("follow-path-matrix-role-sym", panel)
        self.assertNotIn("乘进 ranking", panel)
        self.assertNotIn("低于则禁买", panel)
        self.assertNotIn("follow-path-matrix-viz", panel)
        self.assertNotIn("融合权重（保存时归一化）", panel)
        self.assertNotIn("trade 50%", panel)
        self.assertIn("follow-path-matrix-box", panel)
        self.assertNotIn("follow-path-matrix-field", panel)
        self.assertNotIn("follow-path-matrix-lambda", panel)
        self.assertNotIn("follow-path-matrix-gate-", panel)
        self.assertNotIn('class="follow-path-matrix-gate"', panel)
        self.assertNotIn("follow-path-matrix-grid", panel)
        self.assertIn('data-panel="mode"', panel)
        self.assertIn('data-panel="rank"', panel)
        self.assertNotIn('data-panel="cash"', panel)
        self.assertNotIn("现金地板", panel)
        self.assertNotIn('data-panel="path"', panel)
        self.assertNotIn('data-panel="on"', panel)
        self.assertNotIn('data-panel="gates"', panel)
        self.assertNotIn('name="pm_mode"', panel)
        self.assertNotIn("线性对照", panel)
        self.assertIn('name="pm_rank_enter"', panel)
        self.assertIn('name="pm_rank_enter" min="0" max="10" step="0.1" value="1.2"', panel)
        self.assertIn('name="pm_rank_strong"', panel)
        self.assertIn('name="pm_rank_strong" min="0" max="10" step="0.1" value="1.2"', panel)
        self.assertNotIn('value="0.012"', panel)
        self.assertNotIn('value="0.02"', panel)
        self.assertNotIn('name="pm_cash_floor"', panel)
        self.assertIn('name="pm_fusion_w_trade"', panel)
        self.assertIn('name="pm_fusion_w_nc"', panel)
        self.assertIn('name="pm_w_eod"', panel)
        self.assertIn('name="pm_w_tau"', panel)
        self.assertIn("分数融合", panel)
        self.assertIn("follow-path-matrix-body--row4", panel)
        self.assertNotIn("follow-path-matrix-body--row2", panel)
        self.assertIn('name="pm_y_on_alpha"', panel)
        self.assertIn('name="pm_holdings_mv_cap"', panel)
        self.assertIn("入场 1.2%", panel)
        self.assertIn("强 1.2%", panel)
        self.assertIn("200/500 股", panel)
        self.assertIn("现价 · 200/500 股", panel)
        self.assertNotIn("开盘价 · 200/500 股", panel)
        self.assertIn("paper-rebalance-worker-enabled", panel)
        self.assertIn("paper-rebalance-worker-ledger", panel)
        self.assertIn("paper-rebalance-worker-desk", panel)
        self.assertIn("follow-fold-rebalance-run", panel)
        self.assertIn("自动调仓后台进程", panel)
        self.assertNotIn("100/200 股", panel)
        self.assertNotIn("过强买 200 否则 100", panel)
        self.assertIn("过强买 500 否则 200", panel)
        self.assertNotIn("入场 1%、强 2%", panel)
        self.assertNotIn('name="pm_path_enter"', panel)
        self.assertNotIn('name="pm_y_on_allow"', panel)
        self.assertNotIn('name="pm_require_path_on"', panel)
        self.assertNotIn('name="pm_require_nowcast"', panel)
        exe_ui = self._read("web", "static", "js", "paper", "execution_ui.js")
        self.assertIn("enabled: true", exe_ui)
        self.assertIn('mode: "rank_lots"', exe_ui)
        self.assertIn("pm_rank_enter", exe_ui)
        self.assertIn("rankPctToScore", exe_ui)
        self.assertIn("rankScoreToPct", exe_ui)
        self.assertIn("pm_y_on_alpha", exe_ui)
        self.assertIn("pm_holdings_mv_cap", exe_ui)
        self.assertIn("fillDualScoreForm", exe_ui)
        self.assertIn("collectDualScorePatch", exe_ui)
        self.assertNotIn("pm_enabled", exe_ui)
        self.assertNotIn("pm_cash_floor", exe_ui)
        self.assertNotIn("syncPathMatrixViz", exe_ui)
        paper = self._read("web", "static", "js", "paper.js")
        self.assertIn("collectPathMatrixForm", paper)
        self.assertIn("/api/paper/rebalance/worker", paper)
        self.assertIn("paper-rebalance-worker-enabled", paper)
        self.assertIn("renderPaperRebalanceWorkerDesk", paper)
        self.assertIn("rebalance_desk.js", paper)
        desk_js = self._read("web", "static", "js", "paper", "rebalance_desk.js")
        self.assertIn("今日盯盘状态", desk_js)
        self.assertIn("renderPaperRebalanceWorkerDesk", desk_js)
        self.assertIn('deskChip("is-univ", "持仓"', desk_js)
        self.assertIn('if (!v && cls !== "is-univ") return ""', desk_js)
        self.assertIn('if (rs == null || rs === "") return "—"', desk_js)
        self.assertIn("paper-t0-col-act", desk_js)
        self.assertNotIn("未开", desk_js)
        self.assertIn("last_run_ts", paper)
        self.assertIn(" · 卖 ${", paper)
        css = self._read("web", "static", "css", "follow.css")
        self.assertNotIn(
            ".follow-rebalance-section .paper-t0-worker-panel",
            css,
        )
        self.assertIn(".follow-rebalance-rules-card {", css)
        self.assertNotIn("JSON.stringify({ top_k: 3, limit: 10 })", paper)
        self.assertNotIn('getElementById("paper-rebalance")', paper)
        rules_ui = self._read("web", "static", "js", "paper", "rules_ui.js")
        self.assertNotIn("现金地板", rules_ui)
        report = self._read("web", "static", "js", "paper", "rebalance_report.js")
        self.assertNotIn("现金地板≥", report)
        self.assertIn("cash_below_floor", report)
        self.assertIn("ranking入场≥", report)
        self.assertIn("fmtRankEnterPct", report)
        self.assertIn('role="columnheader" title="y_fuse', report)
        self.assertIn(">y_fuse</div>", report)
        self.assertIn(">rank</div>", report)
        css = self._read("web", "static", "css", "follow.css")
        self.assertNotIn("follow-path-matrix-strategy", css)
        self.assertNotIn("follow-path-matrix-roles", css)
        self.assertNotIn("follow-path-matrix-role", css)
        self.assertNotIn("follow-rebalance-actions", css)
        self.assertNotIn("follow-strategy-readonly", css)
        self.assertNotIn("follow-strategy-link", css)
        self.assertNotIn("follow-path-matrix-viz", css)

    def test_t0_process_tip_has_kline_helpers(self):
        table = self._read("web", "static", "js", "paper", "t0_table.js")
        paper = self._read("web", "static", "js", "paper.js")
        css = self._read("web", "static", "css", "follow.css")
        self.assertIn("data-t0-process-tip", table)
        self.assertIn("miniKlineSvgFromBars", table)
        self.assertIn("wireT0ProcessTips", table)
        self.assertIn("wireT0ProcessTips", paper)
        self.assertNotIn("data-t0-day-detail", table)
        self.assertNotIn("bindT0DayDetailExpand", table)
        self.assertNotIn("buildDayDetailPayload", table)
        self.assertNotIn("resolveDayPriceSpace", table)
        self.assertNotIn("fmtDayPxPairHtml", table)
        self.assertIn("slotClosePxParts", table)
        self.assertIn("/S 映分钟", self._read("web", "static", "js", "paper", "execution_ui.js"))
        self.assertIn("price_space_mismatch", table)
        self.assertNotIn("c_nowcast", table)
        self.assertNotIn("band_upper_pct: r && r.upper_pct", table)
        self.assertNotIn("paper-t0-day-detail", table)
        self.assertIn("paper-t0-process-tip", css)
        self.assertIn("paper-t0-process-kline", css)
        self.assertNotIn("paper-t0-day-detail", css)
        self.assertIn("paper-t0-day-yhat-daily", css)
        self.assertNotIn("paper-t0-day-detail-meta", css)
        self.assertNotIn("paper-t0-day-status", css)
        self.assertNotIn("paper-t0-day-detail-chart", css)
        self.assertNotIn("paper-t0-day-ohlc", css)
        self.assertNotIn("paper-t0-day-yhat-ohlc", css)
        self.assertIn("pickDetailDays", table)
        self.assertNotIn("includeSkippedGateTrace", table)
        self.assertIn("out[loI][5]", table)
        self.assertIn("out[hiI][5]", table)
        self.assertIn(">L ", table)
        self.assertIn(">H ", table)
        self.assertNotIn("ensureT0GateTraceBindings", table)
        self.assertNotIn("点击展开前向门禁", table)
        self.assertNotIn("paper-t0-row-gate-expandable", css)

    def test_execution_ui_fill_form_sets_checkbox_false(self):
        ui = self._read("web", "static", "js", "paper", "execution_ui.js")
        self.assertIn('if (el.type === "checkbox")', ui)
        self.assertIn("el.checked = !!val", ui)
        self.assertIn('set("enabled", t0.enabled !== false)', ui)
        self.assertIn('t0_ratio: 1.0', ui)
        self.assertIn('specKpi("启用", enabledLbl', ui)

    def test_t0_viz_contrib_main_cause_and_attr(self):
        viz = self._read("web", "static", "js", "paper", "t0_viz.js")
        table = self._read("web", "static", "js", "paper", "t0_table.js")
        css = self._read("web", "static", "css", "follow.css")
        paper_js = self._read("web", "static", "js", "paper.js")
        self.assertIn("renderContribSection", viz)
        self.assertIn("paper-t0-viz-pnl-bar", viz)
        self.assertIn("buildSkipTipHtml", viz)
        self.assertIn("wireT0SkipTips", viz)
        self.assertIn("data-skip-tip", viz)
        self.assertIn("wireT0SkipTips", paper_js)
        self.assertIn("leg.skip_reason || leg.note", paper_js)
        self.assertIn("涨停买不到、跌停卖不出、停牌则跳过并留单", paper_js)
        self.assertIn("意向价与现价中点", paper_js)
        self.assertIn("14:50", paper_js)
        self.assertIn("eod_tau_disagree", viz)
        self.assertIn("y_eod_flat", viz)
        self.assertIn("eod_tau_disagree", table)
        self.assertIn("SKIP_CAT_TIP", table)
        self.assertIn(".paper-t0-viz-contrib-meta", css)
        self.assertIn(".paper-t0-viz-contrib-hint", css)
        self.assertIn(".paper-t0-skip-tip", css)
        self.assertIn(".paper-t0-skip-tip-inner", css)
        # 已撤：归因/分票 PnL 增补图 · 方向 PnL 子图
        self.assertNotIn('data-viz="stockpnl"', viz)
        self.assertNotIn('data-viz="tauattr"', viz)
        self.assertNotIn('data-viz="dirpnl"', viz)
        self.assertNotIn("方向 PnL", viz)
        self.assertNotIn("drawDirectionPnl", viz)
        self.assertNotIn("drawAttrPnlBars", viz)
        self.assertNotIn("drawStockContribBars", viz)
        self.assertNotIn("sm.y_tau_enter != null ? sm.y_tau_enter : 0.25", viz)

    def test_follow_panel_v6_close_band_controls(self):
        panel = self._read("web", "static", "partials", "follow_panel.html")
        ui = self._read("web", "static", "js", "paper", "execution_ui.js")
        self.assertIn('name="t0_close_band_delta_pct"', panel)
        self.assertIn(">超额带宽δ%</span>", panel)
        self.assertNotIn(">带宽δ%</span>", panel)
        self.assertIn('name="t0_price_space_gate"', panel)
        self.assertIn('name="t0_price_space_max_dev_pct"', panel)
        self.assertIn('name="t0_price_space_prev_dev_pct"', panel)
        self.assertIn('name="t0_round_ratio"', panel)
        self.assertIn('name="t0_max_position_pct"', panel)
        self.assertNotIn('name="y_trade_strong"', panel)
        self.assertNotIn('name="y_eod_strong"', panel)
        self.assertIn('name="r_tau_enter"', panel)
        self.assertIn('name="r_tau_enter" min="0" max="1.0"', panel)
        self.assertIn(">R入场%</span>", panel)
        self.assertIn('name="y_use_path"', panel)
        self.assertIn('name="y_tau_enter"', panel)
        self.assertIn('name="y_path_enter"', panel)
        self.assertIn('name="y_path_strong"', panel)
        self.assertIn(">path入场%</span>", panel)
        self.assertIn(">τ入场%</span>", panel)
        self.assertIn(">path强%</span>", panel)
        self.assertIn('name="y_complexity_max"', panel)
        self.assertIn('name="y_complexity_max" min="0" max="1.00"', panel)
        self.assertIn('name="y_tpd_max"', panel)
        self.assertIn('name="y_tpd_max" min="0" max="1.00" step="0.01" value="1.00"', panel)
        self.assertIn(">complexity门槛</span>", panel)
        self.assertIn(">tpd门槛</span>", panel)
        self.assertIn("<legend>门槛1</legend>", panel)
        self.assertIn("<legend>门槛2</legend>", panel)
        gate_hint = (
            "|y_τ|、|y_path|、|R̂_τ| 过入场，且 complexity / tpd 过上限。"
            "关启用则本档不参与 OR。缺 path / 分钟缺失见共用区。"
        )
        self.assertEqual(panel.count(gate_hint), 2)
        self.assertNotIn("门槛1 未过时，过本组仍可开腿", panel)
        self.assertNotIn("<legend>收益</legend>", panel)
        self.assertNotIn("<legend>风险</legend>", panel)
        self.assertIn('class="paper-t0-cfg-gates"', panel)
        self.assertIn('class="paper-t0-form-grid is-quad"', panel)
        self.assertEqual(panel.count('class="paper-t0-form-grid is-quad"'), 4)
        self.assertIn('class="paper-t0-form-grid is-oct"', panel)
        css = self._read("web", "static", "css", "follow.css")
        self.assertIn(".paper-t0-form-grid.is-quad", css)
        self.assertIn("repeat(4, minmax(0, 1fr))", css)
        self.assertIn(".paper-t0-form-grid.is-oct", css)
        self.assertIn("repeat(8, minmax(0, 1fr))", css)
        self.assertIn('class="paper-t0-cfg-block is-gate-1"', panel)
        self.assertIn('class="paper-t0-cfg-block is-gate-2"', panel)
        self.assertNotIn('class="paper-t0-cfg-block is-return"', panel)
        self.assertNotIn('class="paper-t0-cfg-block is-risk"', panel)
        self.assertIn('name="y_enter_enabled"', panel)
        self.assertIn('name="y_enter_alt_enabled"', panel)
        self.assertIn('name="y_tau_enter_alt"', panel)
        self.assertIn('name="y_path_enter_alt"', panel)
        self.assertIn('name="r_tau_enter_alt"', panel)
        self.assertIn('name="r_tau_enter_alt" min="0" max="1.0"', panel)
        self.assertIn('name="y_complexity_max_alt"', panel)
        self.assertIn('name="y_tpd_max_alt"', panel)
        self.assertNotIn('name="y_use_next"', panel)
        self.assertNotIn('name="y_next_enter"', panel)
        self.assertNotIn(">next入场%</span>", panel)
        self.assertNotIn(">PATH强%</span>", panel)
        self.assertIn('name="y_tau_leg1_prior_mode"', panel)
        self.assertIn('<option value="score" selected>抬门槛</option>', panel)
        self.assertNotIn('<option value="off" selected>', panel)
        self.assertNotIn('<option value="skip">硬跳过</option>', panel)
        self.assertNotIn("硬跳过", panel)
        self.assertIn('name="y_tau_leg1_prior_risk"', panel)
        self.assertIn('name="y_tau_leg1_prior_risk" min="0" max="100"', panel)
        self.assertIn('Math.min(num("y_tau_leg1_prior_risk", 10), 100)', ui)
        self.assertIn('name="y_tau_leg1_prior_shift_scale"', panel)
        self.assertIn(">shift上限α</span>", panel)
        self.assertIn('name="y_tau_leg1_prior_shift_scale" min="0.1" max="1.0"', panel)
        self.assertIn("ĉ = ĉ_τ", panel)
        self.assertNotIn('name="y_on_allow"', panel)
        self.assertNotIn("is-y-on-allow", panel)
        self.assertNotIn("syncYOnAllowVisibility", ui)
        self.assertNotIn('name="fill_mode_buy_then_sell"', panel)
        self.assertNotIn('name="fill_mode_sell_then_buy"', panel)
        self.assertIn('fill_mode: "trigger"', ui)
        self.assertIn('t0_vs_stance: "independent"', ui)
        self.assertNotIn("<select name=\"t0_vs_stance\"", panel)
        self.assertIn('name="t0_stop_pct_buy_then_sell"', panel)
        self.assertIn('name="must_cover_same_day_sell_then_buy"', panel)
        self.assertIn('name="t0_pm_degrade_sell_then_buy"', panel)
        self.assertIn("t0_close_band_delta_pct", ui)
        self.assertIn("t0_price_space_gate", ui)
        self.assertIn("t0_price_space_max_dev_pct", ui)
        self.assertIn("t0_price_space_prev_dev_pct", ui)
        self.assertIn("昨收差%", panel)
        self.assertNotIn("昨收比差%", panel)
        self.assertIn("|日昨/分昨−1|×100", panel)
        self.assertIn("|日开/分开−1|×100", panel)
        self.assertNotIn("|开盘比−昨收比|", panel)
        tbl = self._read("web", "static", "js", "paper", "t0_table.js")
        self.assertIn("_t0_lock_trade", tbl)
        fmt = self._read("web", "static", "js", "paper", "fmt.js")
        self.assertIn("_t0_lock_trade", fmt)
        self.assertNotIn('name="y_trade_strong"', ui)
        self.assertNotIn("y_trade_strong:", ui)
        self.assertNotIn("y_eod_strong:", ui)
        self.assertIn('Math.min(num("y_tau_enter", 0), 100)', ui)
        self.assertIn('Math.min(num("y_path_enter", 0), 100)', ui)
        self.assertIn('Math.min(num("y_tau_enter_alt", 0), 100)', ui)
        self.assertIn('Math.min(num("y_path_enter_alt", 0), 100)', ui)
        self.assertIn("r_tau_enter", ui)
        self.assertIn("r_tau_enter_alt", ui)
        self.assertIn('"门槛1"', ui)
        self.assertIn('"门槛2"', ui)
        self.assertIn(
            '"门槛1：启用时 |y_τ| / |y_path| / |R̂_τ| 入场 + complexity/tpd 风险"',
            ui,
        )
        self.assertIn(
            '"门槛2：启用时 |y_τ| / |y_path| / |R̂_τ| 入场 + complexity/tpd 风险"',
            ui,
        )
        self.assertNotIn("启用且门槛1 未过时", ui)
        self.assertIn("y_use_path", ui)
        self.assertNotIn("y_use_next", ui)
        self.assertNotIn("y_next_enter", ui)
        self.assertIn("y_path_strong", ui)
        self.assertIn("y_complexity_max", ui)
        self.assertIn("y_tpd_max", ui)
        self.assertIn("y_enter_enabled", ui)
        self.assertIn("y_enter_alt_enabled", ui)
        self.assertNotIn("y_cx_max:", ui)
        self.assertNotIn("y_on_allow: 0.01", ui)
        self.assertIn("y_tau_enter_alt", ui)
        self.assertIn("y_path_enter_alt", ui)
        self.assertIn("y_complexity_max_alt", ui)
        self.assertIn("y_tpd_max_alt", ui)
        self.assertIn("<legend>门槛1</legend>", panel)
        self.assertIn("<legend>门槛2</legend>", panel)
        self.assertIn("y_tau_leg1_prior_mode", ui)
        self.assertIn("y_tau_leg1_prior_risk", ui)
        self.assertIn("y_tau_leg1_prior_shift_scale", ui)
        self.assertIn("ĉ=ĉ_τ", ui)
        self.assertNotIn('set("y_ratio_cut"', ui)
        self.assertNotIn('set("y_tau_map"', ui)
        self.assertNotIn('y_tau_entry_price_mult_buy_then_sell', ui)
        self.assertNotIn('y_prefix_segment_enabled_sell_then_buy', ui)
        self.assertNotIn('y_prefix_upbar_ratio_buy_then_sell', ui)
        self.assertNotIn('y_path_abandon_bars', ui)
        self.assertNotIn('t0_confirm_dev_pct', ui)
        self.assertNotIn('t0_env_one_sided_tau_abs', ui)
        paper_js = self._read("web", "static", "js", "paper.js")
        self.assertIn("applyExecutionToUi", paper_js)
        self.assertIn("保存超时，请重试", paper_js)
        self.assertNotIn("refreshPaperAfterExecution", paper_js)
        save_chunk = paper_js.split("paperT0Form.addEventListener")[1].split("paperPathMatrixForm")[0]
        self.assertIn("applyExecutionToUi", save_chunk)
        self.assertNotIn("renderPaperAccountDetail", save_chunk)
        self.assertNotIn('apiFetch("/api/paper")', save_chunk)

    def test_interpret_request_has_offline(self):
        try:
            from web.schemas import QuantInterpretRequest
        except ImportError:
            self.skipTest("fastapi/pydantic not installed")
        self.assertIn("offline", QuantInterpretRequest.model_fields)

    def test_score_review_ui_removed_shadow_strips_on_tau(self):
        panel = self._read("web", "static", "partials", "quant_panel.html")
        review_js = self._read("web", "static", "js", "quant", "domain_score_review.js")
        self.assertNotIn('id="quant-section-score-review"', panel)
        self.assertNotIn("冻结打分", panel)
        self.assertNotIn("双层 ŷ 复盘", panel)
        self.assertNotIn('id="quant-tau-shadow"', panel)
        self.assertNotIn('id="quant-nowcast-shadow"', panel)
        self.assertIn('id="quant-yhat-residual-shadow"', panel)
        self.assertIn('id="quant-excess-mode-shadow"', panel)
        self.assertNotIn("/api/quant/score-review/tau-shadow", review_js)
        self.assertNotIn("/api/quant/score-review/nowcast-shadow", review_js)
        self.assertNotIn("tau_sign_hit_rate", review_js)
        self.assertNotIn("syncOverviewFromTauShadow", review_js)
        self.assertNotIn("refreshShadowReviews", review_js)

        quant_js = self._read("web", "static", "js", "quant.js")
        self.assertNotIn("tau_shadow 覆盖", quant_js)
        self.assertNotIn("盖住复盘 tau_shadow", quant_js)
        self.assertNotIn("/api/quant/score-review?", review_js)
        self.assertNotIn("/api/quant/score-review/dates", review_js)
        self.assertNotIn("/api/quant/score-review/hit-series", review_js)
        self.assertNotIn("/api/quant/score-ledger/freeze", review_js)
        self.assertNotIn("/api/quant/score-ledger/stock-panel", review_js)
        self.assertNotIn("/api/quant/score-ledger/delete", review_js)
        self.assertNotIn("/api/quant/score-outcomes/fill", review_js)
        self.assertNotIn("quant-score-review-run", review_js)

        watching = self._read("web", "static", "js", "quant", "domain_watching.js")
        self.assertIn("/api/quant/score-ledger/series", watching)
        self.assertNotIn("/api/quant/score-ledger/stock-panel", watching)
        self.assertNotIn("/api/quant/score-ledger/freeze", watching)

        viz = self._read("web", "static", "js", "quant", "yhat_viz.js")
        css = self._read("web", "static", "css", "quant.css")
        self.assertNotIn("paintHitSparkline", viz)
        self.assertNotIn("quant-score-review-table", css)
        self.assertNotIn("quant-score-ledger-chip", css)
        self.assertNotIn("#quant-score-review-panel-wrap", css)
        self.assertNotIn("#quant-section-score-review", css)
        self.assertNotIn(".quant-score-review-tau", css)
        self.assertNotIn(".quant-tau-strip", css)

    def test_score_calibration_ui_removed(self):
        panel = self._read("web", "static", "partials", "quant_panel.html")
        review_js = self._read("web", "static", "js", "quant", "domain_score_review.js")
        self.assertNotIn('id="quant-section-score-cal"', panel)
        self.assertNotIn("拟合校准", panel)
        self.assertNotIn("校准 g(ŷ)", panel)
        self.assertNotIn("/api/quant/score-calibration/", review_js)
        self.assertNotIn("refreshCalibrationPanel", review_js)
        self.assertNotIn("quant-score-cal-fit", review_js)

        viz = self._read("web", "static", "js", "quant", "yhat_viz.js")
        tip = self._read("web", "static", "js", "score_tooltip.js")
        fmt = self._read("web", "static", "js", "paper", "fmt.js")
        self.assertNotIn("mountCalibrationCurve", viz)
        self.assertNotIn("paintCalibrationCurve", viz)
        self.assertNotIn("formatCalibrationSection", tip)
        self.assertNotIn("resolveCalTradeScore", fmt)
        self.assertNotIn("watching-score-cal", tip)


    def test_strategy_page_dead_factor_lab_removed(self):
        panel = self._read("web", "static", "partials", "strategy_panel.html")
        strat_js = self._read("web", "static", "js", "quant", "domain_strategy.js")
        quant_js = self._read("web", "static", "js", "quant.js")
        export_js = self._read("web", "static", "js", "quant", "domain_export.js")
        self.assertNotIn("strategy-sample-ops", panel)
        self.assertNotIn("strategy-logic-ref", panel)
        self.assertNotIn("策略逻辑参考", panel)
        self.assertNotIn("样本与闸门", panel)
        self.assertNotIn("strategy-weight-suggest-run", panel)
        self.assertNotIn("strategy-factor-status", panel)
        self.assertNotIn("strategy-factor-lab", panel)
        self.assertNotIn("runStrategyWeightSuggest", strat_js)
        self.assertNotIn("loadConfigDiffPreview", strat_js)
        self.assertNotIn("strategy-weight-suggest-run", quant_js)
        self.assertNotIn("quant-diff-preview", quant_js)
        self.assertNotIn("loadConfigDiffPreview", export_js)
        css = self._read("web", "static", "css", "strategy.css")
        self.assertNotIn("strategy-param-table", css)
        self.assertNotIn("strategy-risk-limits-grid", css)
        self.assertNotIn("strategy-card-chips", css)
        self.assertNotIn("strategy-hero-lead", css)
        self.assertNotIn("strategy-secondary-band", css)
        self.assertNotIn("strategy-logic-ref", css)
        self.assertIn("strategy-factor-dict", panel)
        self.assertNotIn("strategy-risk-audit-fold", panel)
        self.assertNotIn("strategy-risk-audit", panel)
        self.assertNotIn("loadStrategyRiskAudit", strat_js)
        self.assertNotIn("strategy-risk-audit-fold", quant_js)
        self.assertIn("strategy-market-context", panel)
        self.assertIn("strategy-regime-board", panel)
        self.assertIn("strategy-regime-body", panel)
        self.assertIn("strategy-mctx-regime-pill", panel)
        self.assertIn("strategy-regime-body", strat_js)
        self.assertIn("renderRegimeBoard", strat_js)
        self.assertIn("strategy-regime-axis", strat_js)
        self.assertIn("strategy-regime-spectrum", css)
        self.assertIn("strategy-regime-needle-val", css)
        self.assertIn("压单票与行业上限", panel)
        self.assertNotIn("strategy-regime-sub", panel)
        self.assertNotIn("strategy-mctx-board", panel)
        self.assertNotIn("盘前 prior · Regime", panel)
        self.assertNotIn("strategy-path-rail", panel)
        self.assertNotIn("strategy-path-step", quant_js)
        self.assertNotIn("ingest…", strat_js)
        self.assertNotIn("正在刷新盘前快照", strat_js)
        self.assertNotIn('btn.classList.add("is-busy")', strat_js)
        self.assertIn('setMctxHeadStatus((head && head.textContent) || "", { busy: true })', strat_js)
        self.assertIn('id="strategy-regime-board"', panel)
        self.assertIn('id="strategy-market-context"', panel)
        self.assertIn("strategy-mctx-head-status", panel)
        self.assertNotIn("strategy-mctx-hint", panel)
        self.assertNotIn("四路闸门", panel)
        self.assertNotIn("mode gate", strat_js)
        self.assertNotIn("off · 关闭", panel)
        self.assertIn("strategy-mctx-matrix", panel)
        self.assertIn("strategy-mctx-panels", panel)
        self.assertIn("strategy-mctx-unit", panel)
        self.assertIn("strategy-mctx-boxes", panel)
        self.assertIn(">跨市场<", panel)
        self.assertIn(">情绪<", panel)
        self.assertIn(">监管<", panel)
        self.assertIn(">IPO<", panel)
        self.assertIn("strategy-mctx-unit[data-k=", strat_js)
        self.assertNotIn("quant-control-band", panel)
        self.assertNotIn("quant-oos-band", panel)
        self.assertNotIn("strategy-mctx-params-modes", panel)
        self.assertNotIn("strategy-mctx-params-actions", panel)
        self.assertIn("四闸缩仓 / 拦开仓", panel)
        self.assertIn("人审写入 signal_config", panel)
        self.assertEqual(panel.count('id="strategy-mctx-mode"'), 1)
        self.assertEqual(panel.count('id="strategy-mctx-save"'), 1)
        self.assertNotIn('id="strategy-mctx-save" class="dialog-btn secondary"', panel)
        self.assertNotIn('id="strategy-mctx-refresh" class="dialog-btn secondary"', panel)
        self.assertIn('id="strategy-mctx-mode"', panel)
        self.assertNotIn("strategy-mctx-channels", panel)
        self.assertNotIn("strategy-mctx-channel", css)
        self.assertNotIn('name="strategy-mctx-mode"', panel)
        self.assertNotIn("strategy-mctx-extra-grid", panel)
        self.assertIn("repeat(4, minmax(0, 1fr))", css)
        self.assertIn("minmax(0, 1fr) minmax(0, 1fr)", css)
        self.assertIn('[data-k="cross_market"]', css)
        self.assertIn('[data-k="sentiment"]', css)
        self.assertIn('[data-k="regulatory"]', css)
        self.assertIn('[data-k="ipo"]', css)
        self.assertIn(".strategy-mctx-box--check input[type=\"checkbox\"]", css)
        self.assertNotIn("strategy-sentiment-prior", panel)
        self.assertNotIn("strategy-prior-save", panel)
        self.assertNotIn('name="strategy-prior-mode"', panel)
        self.assertNotIn("saveStrategySentimentPrior", strat_js)
        self.assertNotIn("loadSentimentPriorForm", strat_js)
        self.assertIn("strategy-market-context", quant_js)
        self.assertNotIn("strategy-promote-lab", panel)
        self.assertNotIn("strategy-promote-btn", panel)
        self.assertNotIn("晋升快照", panel)
        self.assertNotIn("promoteStrategy", strat_js)
        self.assertNotIn("strategy-promote-btn", quant_js)
        self.assertNotIn("strategy-scoring-floors", panel)
        self.assertNotIn("strategy-dual-score", panel)
        self.assertNotIn("strategy-floor-save", panel)
        self.assertNotIn("strategy-dual-save", panel)
        self.assertNotIn("saveStrategyScoringFloors", strat_js)
        self.assertNotIn("saveStrategyDualScore", strat_js)
        self.assertNotIn("loadDualScoreForm", strat_js)
        self.assertNotIn("#strategy-dual-score", css)
        self.assertNotIn("strategy-floors-form", css)
        self.assertNotIn("strategy-inline-field", css)

    def test_desk_page_heads_share_title_scale(self):
        for name in ("strategy", "watching", "follow", "replay", "quant"):
            css = self._read("web", "static", "css", f"{name}.css")
            self.assertIn("--sys-fs-title, 1.125rem", css, name)
            self.assertIn("letter-spacing: 0.14em", css, name)
            self.assertIn("font-weight: var(--sys-fw-display, 700)", css, name)
            self.assertIn("height: 28px", css, name)
            self.assertIn("padding: 2px 0 6px", css, name)
            self.assertNotRegex(
                css,
                r"\.quant-head h2\s*\{[^}]*font-size:\s*16px",
                msg=f"{name}: leftover 16px page title",
            )
            self.assertNotRegex(
                css,
                r"\.quant-head:has\(\+",
                msg=f"{name}: leftover :has(+ page) head override",
            )
        follow = self._read("web", "static", "css", "follow.css")
        self.assertNotIn("padding: 0 0 16px", follow)
        self.assertNotRegex(
            follow,
            r"\.follow-desk-badge\s*\{[^}]*border-radius:\s*999px",
            msg="follow desk badge must not be a 22/24px pill",
        )

    def test_domain_strategy_js_braces_balanced(self):
        """多余 } 会让 installStrategy 提前结束，return 变成模块顶层，/replay 整页 JS 挂不上。"""
        src = self._read("web", "static", "js", "quant", "domain_strategy.js")
        depth = 0
        in_s = None
        esc = False
        in_line = False
        in_block = False
        i = 0
        n = len(src)
        while i < n:
            c = src[i]
            nxt = src[i + 1] if i + 1 < n else ""
            if in_line:
                if c == "\n":
                    in_line = False
                i += 1
                continue
            if in_block:
                if c == "*" and nxt == "/":
                    in_block = False
                    i += 2
                    continue
                i += 1
                continue
            if in_s:
                if esc:
                    esc = False
                elif c == "\\":
                    esc = True
                elif c == in_s:
                    in_s = None
                i += 1
                continue
            if c in "\"'`":
                in_s = c
                i += 1
                continue
            if c == "/" and nxt == "/":
                in_line = True
                i += 2
                continue
            if c == "/" and nxt == "*":
                in_block = True
                i += 2
                continue
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                self.assertGreaterEqual(depth, 0, "extra } before end of domain_strategy.js")
            i += 1
        self.assertEqual(depth, 0)
        quant_js = self._read("web", "static", "js", "quant.js")
        self.assertIn(
            "domain_strategy.js?v=${encodeURIComponent(_QV)}",
            quant_js,
        )

    def test_watching_news_empty_copy(self):
        watching = self._read("web", "static", "js", "quant", "domain_watching.js")
        self.assertNotIn("暂无资讯，跳过 AI 分析", watching)
        self.assertNotIn('aiStatus.textContent = "无资讯"', watching)
        render = self._read("web", "static", "js", "quant", "watching_render.js")
        self.assertIn('data.error || "暂无资讯"', render)
        self.assertNotIn('data.error || "无资讯"', render)
        self.assertNotIn('data.error || "暂无标题"', render)


if __name__ == "__main__":
    unittest.main()
